// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/audit/audit_log.proto

package com.google.cloud.audit;

/**
 * <pre>
 * Common audit log format for Google Cloud Platform API operations.
 * </pre>
 *
 * Protobuf type {@code google.cloud.audit.AuditLog}
 */
public  final class AuditLog extends
    com.google.protobuf.GeneratedMessageLite<
        AuditLog, AuditLog.Builder> implements
    // @@protoc_insertion_point(message_implements:google.cloud.audit.AuditLog)
    AuditLogOrBuilder {
  private AuditLog() {
    serviceName_ = "";
    methodName_ = "";
    resourceName_ = "";
    authorizationInfo_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int SERVICE_NAME_FIELD_NUMBER = 7;
  private java.lang.String serviceName_;
  /**
   * <pre>
   * The name of the API service performing the operation. For example,
   * `"datastore.googleapis.com"`.
   * </pre>
   *
   * <code>optional string service_name = 7;</code>
   */
  public java.lang.String getServiceName() {
    return serviceName_;
  }
  /**
   * <pre>
   * The name of the API service performing the operation. For example,
   * `"datastore.googleapis.com"`.
   * </pre>
   *
   * <code>optional string service_name = 7;</code>
   */
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serviceName_);
  }
  /**
   * <pre>
   * The name of the API service performing the operation. For example,
   * `"datastore.googleapis.com"`.
   * </pre>
   *
   * <code>optional string service_name = 7;</code>
   */
  private void setServiceName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    serviceName_ = value;
  }
  /**
   * <pre>
   * The name of the API service performing the operation. For example,
   * `"datastore.googleapis.com"`.
   * </pre>
   *
   * <code>optional string service_name = 7;</code>
   */
  private void clearServiceName() {
    
    serviceName_ = getDefaultInstance().getServiceName();
  }
  /**
   * <pre>
   * The name of the API service performing the operation. For example,
   * `"datastore.googleapis.com"`.
   * </pre>
   *
   * <code>optional string service_name = 7;</code>
   */
  private void setServiceNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    serviceName_ = value.toStringUtf8();
  }

  public static final int METHOD_NAME_FIELD_NUMBER = 8;
  private java.lang.String methodName_;
  /**
   * <pre>
   * The name of the service method or operation.
   * For API calls, this should be the name of the API method.
   * For example,
   *     "google.datastore.v1.Datastore.RunQuery"
   *     "google.logging.v1.LoggingService.DeleteLog"
   * </pre>
   *
   * <code>optional string method_name = 8;</code>
   */
  public java.lang.String getMethodName() {
    return methodName_;
  }
  /**
   * <pre>
   * The name of the service method or operation.
   * For API calls, this should be the name of the API method.
   * For example,
   *     "google.datastore.v1.Datastore.RunQuery"
   *     "google.logging.v1.LoggingService.DeleteLog"
   * </pre>
   *
   * <code>optional string method_name = 8;</code>
   */
  public com.google.protobuf.ByteString
      getMethodNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(methodName_);
  }
  /**
   * <pre>
   * The name of the service method or operation.
   * For API calls, this should be the name of the API method.
   * For example,
   *     "google.datastore.v1.Datastore.RunQuery"
   *     "google.logging.v1.LoggingService.DeleteLog"
   * </pre>
   *
   * <code>optional string method_name = 8;</code>
   */
  private void setMethodName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    methodName_ = value;
  }
  /**
   * <pre>
   * The name of the service method or operation.
   * For API calls, this should be the name of the API method.
   * For example,
   *     "google.datastore.v1.Datastore.RunQuery"
   *     "google.logging.v1.LoggingService.DeleteLog"
   * </pre>
   *
   * <code>optional string method_name = 8;</code>
   */
  private void clearMethodName() {
    
    methodName_ = getDefaultInstance().getMethodName();
  }
  /**
   * <pre>
   * The name of the service method or operation.
   * For API calls, this should be the name of the API method.
   * For example,
   *     "google.datastore.v1.Datastore.RunQuery"
   *     "google.logging.v1.LoggingService.DeleteLog"
   * </pre>
   *
   * <code>optional string method_name = 8;</code>
   */
  private void setMethodNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    methodName_ = value.toStringUtf8();
  }

  public static final int RESOURCE_NAME_FIELD_NUMBER = 11;
  private java.lang.String resourceName_;
  /**
   * <pre>
   * The resource or collection that is the target of the operation.
   * The name is a scheme-less URI, not including the API service name.
   * For example:
   *     "shelves/SHELF_ID/books"
   *     "shelves/SHELF_ID/books/BOOK_ID"
   * </pre>
   *
   * <code>optional string resource_name = 11;</code>
   */
  public java.lang.String getResourceName() {
    return resourceName_;
  }
  /**
   * <pre>
   * The resource or collection that is the target of the operation.
   * The name is a scheme-less URI, not including the API service name.
   * For example:
   *     "shelves/SHELF_ID/books"
   *     "shelves/SHELF_ID/books/BOOK_ID"
   * </pre>
   *
   * <code>optional string resource_name = 11;</code>
   */
  public com.google.protobuf.ByteString
      getResourceNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(resourceName_);
  }
  /**
   * <pre>
   * The resource or collection that is the target of the operation.
   * The name is a scheme-less URI, not including the API service name.
   * For example:
   *     "shelves/SHELF_ID/books"
   *     "shelves/SHELF_ID/books/BOOK_ID"
   * </pre>
   *
   * <code>optional string resource_name = 11;</code>
   */
  private void setResourceName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    resourceName_ = value;
  }
  /**
   * <pre>
   * The resource or collection that is the target of the operation.
   * The name is a scheme-less URI, not including the API service name.
   * For example:
   *     "shelves/SHELF_ID/books"
   *     "shelves/SHELF_ID/books/BOOK_ID"
   * </pre>
   *
   * <code>optional string resource_name = 11;</code>
   */
  private void clearResourceName() {
    
    resourceName_ = getDefaultInstance().getResourceName();
  }
  /**
   * <pre>
   * The resource or collection that is the target of the operation.
   * The name is a scheme-less URI, not including the API service name.
   * For example:
   *     "shelves/SHELF_ID/books"
   *     "shelves/SHELF_ID/books/BOOK_ID"
   * </pre>
   *
   * <code>optional string resource_name = 11;</code>
   */
  private void setResourceNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    resourceName_ = value.toStringUtf8();
  }

  public static final int NUM_RESPONSE_ITEMS_FIELD_NUMBER = 12;
  private long numResponseItems_;
  /**
   * <pre>
   * The number of items returned from a List or Query API method,
   * if applicable.
   * </pre>
   *
   * <code>optional int64 num_response_items = 12;</code>
   */
  public long getNumResponseItems() {
    return numResponseItems_;
  }
  /**
   * <pre>
   * The number of items returned from a List or Query API method,
   * if applicable.
   * </pre>
   *
   * <code>optional int64 num_response_items = 12;</code>
   */
  private void setNumResponseItems(long value) {
    
    numResponseItems_ = value;
  }
  /**
   * <pre>
   * The number of items returned from a List or Query API method,
   * if applicable.
   * </pre>
   *
   * <code>optional int64 num_response_items = 12;</code>
   */
  private void clearNumResponseItems() {
    
    numResponseItems_ = 0L;
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private com.google.rpc.Status status_;
  /**
   * <pre>
   * The status of the overall operation.
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <pre>
   * The status of the overall operation.
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   */
  public com.google.rpc.Status getStatus() {
    return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * The status of the overall operation.
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   */
  private void setStatus(com.google.rpc.Status value) {
    if (value == null) {
      throw new NullPointerException();
    }
    status_ = value;
    
    }
  /**
   * <pre>
   * The status of the overall operation.
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   */
  private void setStatus(
      com.google.rpc.Status.Builder builderForValue) {
    status_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * The status of the overall operation.
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   */
  private void mergeStatus(com.google.rpc.Status value) {
    if (status_ != null &&
        status_ != com.google.rpc.Status.getDefaultInstance()) {
      status_ =
        com.google.rpc.Status.newBuilder(status_).mergeFrom(value).buildPartial();
    } else {
      status_ = value;
    }
    
  }
  /**
   * <pre>
   * The status of the overall operation.
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   */
  private void clearStatus() {  status_ = null;
    
  }

  public static final int AUTHENTICATION_INFO_FIELD_NUMBER = 3;
  private com.google.cloud.audit.AuthenticationInfo authenticationInfo_;
  /**
   * <pre>
   * Authentication information.
   * </pre>
   *
   * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
   */
  public boolean hasAuthenticationInfo() {
    return authenticationInfo_ != null;
  }
  /**
   * <pre>
   * Authentication information.
   * </pre>
   *
   * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
   */
  public com.google.cloud.audit.AuthenticationInfo getAuthenticationInfo() {
    return authenticationInfo_ == null ? com.google.cloud.audit.AuthenticationInfo.getDefaultInstance() : authenticationInfo_;
  }
  /**
   * <pre>
   * Authentication information.
   * </pre>
   *
   * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
   */
  private void setAuthenticationInfo(com.google.cloud.audit.AuthenticationInfo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    authenticationInfo_ = value;
    
    }
  /**
   * <pre>
   * Authentication information.
   * </pre>
   *
   * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
   */
  private void setAuthenticationInfo(
      com.google.cloud.audit.AuthenticationInfo.Builder builderForValue) {
    authenticationInfo_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * Authentication information.
   * </pre>
   *
   * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
   */
  private void mergeAuthenticationInfo(com.google.cloud.audit.AuthenticationInfo value) {
    if (authenticationInfo_ != null &&
        authenticationInfo_ != com.google.cloud.audit.AuthenticationInfo.getDefaultInstance()) {
      authenticationInfo_ =
        com.google.cloud.audit.AuthenticationInfo.newBuilder(authenticationInfo_).mergeFrom(value).buildPartial();
    } else {
      authenticationInfo_ = value;
    }
    
  }
  /**
   * <pre>
   * Authentication information.
   * </pre>
   *
   * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
   */
  private void clearAuthenticationInfo() {  authenticationInfo_ = null;
    
  }

  public static final int AUTHORIZATION_INFO_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.ProtobufList<com.google.cloud.audit.AuthorizationInfo> authorizationInfo_;
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  public java.util.List<com.google.cloud.audit.AuthorizationInfo> getAuthorizationInfoList() {
    return authorizationInfo_;
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  public java.util.List<? extends com.google.cloud.audit.AuthorizationInfoOrBuilder> 
      getAuthorizationInfoOrBuilderList() {
    return authorizationInfo_;
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  public int getAuthorizationInfoCount() {
    return authorizationInfo_.size();
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  public com.google.cloud.audit.AuthorizationInfo getAuthorizationInfo(int index) {
    return authorizationInfo_.get(index);
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  public com.google.cloud.audit.AuthorizationInfoOrBuilder getAuthorizationInfoOrBuilder(
      int index) {
    return authorizationInfo_.get(index);
  }
  private void ensureAuthorizationInfoIsMutable() {
    if (!authorizationInfo_.isModifiable()) {
      authorizationInfo_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(authorizationInfo_);
     }
  }

  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void setAuthorizationInfo(
      int index, com.google.cloud.audit.AuthorizationInfo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureAuthorizationInfoIsMutable();
    authorizationInfo_.set(index, value);
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void setAuthorizationInfo(
      int index, com.google.cloud.audit.AuthorizationInfo.Builder builderForValue) {
    ensureAuthorizationInfoIsMutable();
    authorizationInfo_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void addAuthorizationInfo(com.google.cloud.audit.AuthorizationInfo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureAuthorizationInfoIsMutable();
    authorizationInfo_.add(value);
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void addAuthorizationInfo(
      int index, com.google.cloud.audit.AuthorizationInfo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureAuthorizationInfoIsMutable();
    authorizationInfo_.add(index, value);
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void addAuthorizationInfo(
      com.google.cloud.audit.AuthorizationInfo.Builder builderForValue) {
    ensureAuthorizationInfoIsMutable();
    authorizationInfo_.add(builderForValue.build());
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void addAuthorizationInfo(
      int index, com.google.cloud.audit.AuthorizationInfo.Builder builderForValue) {
    ensureAuthorizationInfoIsMutable();
    authorizationInfo_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void addAllAuthorizationInfo(
      java.lang.Iterable<? extends com.google.cloud.audit.AuthorizationInfo> values) {
    ensureAuthorizationInfoIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, authorizationInfo_);
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void clearAuthorizationInfo() {
    authorizationInfo_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Authorization information. If there are multiple
   * resources or permissions involved, then there is
   * one AuthorizationInfo element for each {resource, permission} tuple.
   * </pre>
   *
   * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
   */
  private void removeAuthorizationInfo(int index) {
    ensureAuthorizationInfoIsMutable();
    authorizationInfo_.remove(index);
  }

  public static final int REQUEST_METADATA_FIELD_NUMBER = 4;
  private com.google.cloud.audit.RequestMetadata requestMetadata_;
  /**
   * <pre>
   * Metadata about the operation.
   * </pre>
   *
   * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
   */
  public boolean hasRequestMetadata() {
    return requestMetadata_ != null;
  }
  /**
   * <pre>
   * Metadata about the operation.
   * </pre>
   *
   * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
   */
  public com.google.cloud.audit.RequestMetadata getRequestMetadata() {
    return requestMetadata_ == null ? com.google.cloud.audit.RequestMetadata.getDefaultInstance() : requestMetadata_;
  }
  /**
   * <pre>
   * Metadata about the operation.
   * </pre>
   *
   * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
   */
  private void setRequestMetadata(com.google.cloud.audit.RequestMetadata value) {
    if (value == null) {
      throw new NullPointerException();
    }
    requestMetadata_ = value;
    
    }
  /**
   * <pre>
   * Metadata about the operation.
   * </pre>
   *
   * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
   */
  private void setRequestMetadata(
      com.google.cloud.audit.RequestMetadata.Builder builderForValue) {
    requestMetadata_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * Metadata about the operation.
   * </pre>
   *
   * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
   */
  private void mergeRequestMetadata(com.google.cloud.audit.RequestMetadata value) {
    if (requestMetadata_ != null &&
        requestMetadata_ != com.google.cloud.audit.RequestMetadata.getDefaultInstance()) {
      requestMetadata_ =
        com.google.cloud.audit.RequestMetadata.newBuilder(requestMetadata_).mergeFrom(value).buildPartial();
    } else {
      requestMetadata_ = value;
    }
    
  }
  /**
   * <pre>
   * Metadata about the operation.
   * </pre>
   *
   * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
   */
  private void clearRequestMetadata() {  requestMetadata_ = null;
    
  }

  public static final int REQUEST_FIELD_NUMBER = 16;
  private com.google.protobuf.Struct request_;
  /**
   * <pre>
   * The operation request. This may not include all request parameters,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct request = 16;</code>
   */
  public boolean hasRequest() {
    return request_ != null;
  }
  /**
   * <pre>
   * The operation request. This may not include all request parameters,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct request = 16;</code>
   */
  public com.google.protobuf.Struct getRequest() {
    return request_ == null ? com.google.protobuf.Struct.getDefaultInstance() : request_;
  }
  /**
   * <pre>
   * The operation request. This may not include all request parameters,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct request = 16;</code>
   */
  private void setRequest(com.google.protobuf.Struct value) {
    if (value == null) {
      throw new NullPointerException();
    }
    request_ = value;
    
    }
  /**
   * <pre>
   * The operation request. This may not include all request parameters,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct request = 16;</code>
   */
  private void setRequest(
      com.google.protobuf.Struct.Builder builderForValue) {
    request_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * The operation request. This may not include all request parameters,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct request = 16;</code>
   */
  private void mergeRequest(com.google.protobuf.Struct value) {
    if (request_ != null &&
        request_ != com.google.protobuf.Struct.getDefaultInstance()) {
      request_ =
        com.google.protobuf.Struct.newBuilder(request_).mergeFrom(value).buildPartial();
    } else {
      request_ = value;
    }
    
  }
  /**
   * <pre>
   * The operation request. This may not include all request parameters,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct request = 16;</code>
   */
  private void clearRequest() {  request_ = null;
    
  }

  public static final int RESPONSE_FIELD_NUMBER = 17;
  private com.google.protobuf.Struct response_;
  /**
   * <pre>
   * The operation response. This may not include all response elements,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct response = 17;</code>
   */
  public boolean hasResponse() {
    return response_ != null;
  }
  /**
   * <pre>
   * The operation response. This may not include all response elements,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct response = 17;</code>
   */
  public com.google.protobuf.Struct getResponse() {
    return response_ == null ? com.google.protobuf.Struct.getDefaultInstance() : response_;
  }
  /**
   * <pre>
   * The operation response. This may not include all response elements,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct response = 17;</code>
   */
  private void setResponse(com.google.protobuf.Struct value) {
    if (value == null) {
      throw new NullPointerException();
    }
    response_ = value;
    
    }
  /**
   * <pre>
   * The operation response. This may not include all response elements,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct response = 17;</code>
   */
  private void setResponse(
      com.google.protobuf.Struct.Builder builderForValue) {
    response_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * The operation response. This may not include all response elements,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct response = 17;</code>
   */
  private void mergeResponse(com.google.protobuf.Struct value) {
    if (response_ != null &&
        response_ != com.google.protobuf.Struct.getDefaultInstance()) {
      response_ =
        com.google.protobuf.Struct.newBuilder(response_).mergeFrom(value).buildPartial();
    } else {
      response_ = value;
    }
    
  }
  /**
   * <pre>
   * The operation response. This may not include all response elements,
   * such as those that are too large, privacy-sensitive, or duplicated
   * elsewhere in the log record.
   * It should never include user-generated data, such as file contents.
   * When the JSON object represented here has a proto equivalent, the proto
   * name will be indicated in the `&#64;type` property.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct response = 17;</code>
   */
  private void clearResponse() {  response_ = null;
    
  }

  public static final int SERVICE_DATA_FIELD_NUMBER = 15;
  private com.google.protobuf.Any serviceData_;
  /**
   * <pre>
   * Other service-specific data about the request, response, and other
   * activities.
   * </pre>
   *
   * <code>optional .google.protobuf.Any service_data = 15;</code>
   */
  public boolean hasServiceData() {
    return serviceData_ != null;
  }
  /**
   * <pre>
   * Other service-specific data about the request, response, and other
   * activities.
   * </pre>
   *
   * <code>optional .google.protobuf.Any service_data = 15;</code>
   */
  public com.google.protobuf.Any getServiceData() {
    return serviceData_ == null ? com.google.protobuf.Any.getDefaultInstance() : serviceData_;
  }
  /**
   * <pre>
   * Other service-specific data about the request, response, and other
   * activities.
   * </pre>
   *
   * <code>optional .google.protobuf.Any service_data = 15;</code>
   */
  private void setServiceData(com.google.protobuf.Any value) {
    if (value == null) {
      throw new NullPointerException();
    }
    serviceData_ = value;
    
    }
  /**
   * <pre>
   * Other service-specific data about the request, response, and other
   * activities.
   * </pre>
   *
   * <code>optional .google.protobuf.Any service_data = 15;</code>
   */
  private void setServiceData(
      com.google.protobuf.Any.Builder builderForValue) {
    serviceData_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * Other service-specific data about the request, response, and other
   * activities.
   * </pre>
   *
   * <code>optional .google.protobuf.Any service_data = 15;</code>
   */
  private void mergeServiceData(com.google.protobuf.Any value) {
    if (serviceData_ != null &&
        serviceData_ != com.google.protobuf.Any.getDefaultInstance()) {
      serviceData_ =
        com.google.protobuf.Any.newBuilder(serviceData_).mergeFrom(value).buildPartial();
    } else {
      serviceData_ = value;
    }
    
  }
  /**
   * <pre>
   * Other service-specific data about the request, response, and other
   * activities.
   * </pre>
   *
   * <code>optional .google.protobuf.Any service_data = 15;</code>
   */
  private void clearServiceData() {  serviceData_ = null;
    
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != null) {
      output.writeMessage(2, getStatus());
    }
    if (authenticationInfo_ != null) {
      output.writeMessage(3, getAuthenticationInfo());
    }
    if (requestMetadata_ != null) {
      output.writeMessage(4, getRequestMetadata());
    }
    if (!serviceName_.isEmpty()) {
      output.writeString(7, getServiceName());
    }
    if (!methodName_.isEmpty()) {
      output.writeString(8, getMethodName());
    }
    for (int i = 0; i < authorizationInfo_.size(); i++) {
      output.writeMessage(9, authorizationInfo_.get(i));
    }
    if (!resourceName_.isEmpty()) {
      output.writeString(11, getResourceName());
    }
    if (numResponseItems_ != 0L) {
      output.writeInt64(12, numResponseItems_);
    }
    if (serviceData_ != null) {
      output.writeMessage(15, getServiceData());
    }
    if (request_ != null) {
      output.writeMessage(16, getRequest());
    }
    if (response_ != null) {
      output.writeMessage(17, getResponse());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStatus());
    }
    if (authenticationInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAuthenticationInfo());
    }
    if (requestMetadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRequestMetadata());
    }
    if (!serviceName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(7, getServiceName());
    }
    if (!methodName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(8, getMethodName());
    }
    for (int i = 0; i < authorizationInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, authorizationInfo_.get(i));
    }
    if (!resourceName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(11, getResourceName());
    }
    if (numResponseItems_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, numResponseItems_);
    }
    if (serviceData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getServiceData());
    }
    if (request_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, getRequest());
    }
    if (response_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, getResponse());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.cloud.audit.AuditLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.cloud.audit.AuditLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.cloud.audit.AuditLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.cloud.audit.AuditLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.cloud.audit.AuditLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuditLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.cloud.audit.AuditLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuditLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.cloud.audit.AuditLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuditLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.audit.AuditLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Common audit log format for Google Cloud Platform API operations.
   * </pre>
   *
   * Protobuf type {@code google.cloud.audit.AuditLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.cloud.audit.AuditLog, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.audit.AuditLog)
      com.google.cloud.audit.AuditLogOrBuilder {
    // Construct using com.google.cloud.audit.AuditLog.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The name of the API service performing the operation. For example,
     * `"datastore.googleapis.com"`.
     * </pre>
     *
     * <code>optional string service_name = 7;</code>
     */
    public java.lang.String getServiceName() {
      return instance.getServiceName();
    }
    /**
     * <pre>
     * The name of the API service performing the operation. For example,
     * `"datastore.googleapis.com"`.
     * </pre>
     *
     * <code>optional string service_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      return instance.getServiceNameBytes();
    }
    /**
     * <pre>
     * The name of the API service performing the operation. For example,
     * `"datastore.googleapis.com"`.
     * </pre>
     *
     * <code>optional string service_name = 7;</code>
     */
    public Builder setServiceName(
        java.lang.String value) {
      copyOnWrite();
      instance.setServiceName(value);
      return this;
    }
    /**
     * <pre>
     * The name of the API service performing the operation. For example,
     * `"datastore.googleapis.com"`.
     * </pre>
     *
     * <code>optional string service_name = 7;</code>
     */
    public Builder clearServiceName() {
      copyOnWrite();
      instance.clearServiceName();
      return this;
    }
    /**
     * <pre>
     * The name of the API service performing the operation. For example,
     * `"datastore.googleapis.com"`.
     * </pre>
     *
     * <code>optional string service_name = 7;</code>
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServiceNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * The name of the service method or operation.
     * For API calls, this should be the name of the API method.
     * For example,
     *     "google.datastore.v1.Datastore.RunQuery"
     *     "google.logging.v1.LoggingService.DeleteLog"
     * </pre>
     *
     * <code>optional string method_name = 8;</code>
     */
    public java.lang.String getMethodName() {
      return instance.getMethodName();
    }
    /**
     * <pre>
     * The name of the service method or operation.
     * For API calls, this should be the name of the API method.
     * For example,
     *     "google.datastore.v1.Datastore.RunQuery"
     *     "google.logging.v1.LoggingService.DeleteLog"
     * </pre>
     *
     * <code>optional string method_name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      return instance.getMethodNameBytes();
    }
    /**
     * <pre>
     * The name of the service method or operation.
     * For API calls, this should be the name of the API method.
     * For example,
     *     "google.datastore.v1.Datastore.RunQuery"
     *     "google.logging.v1.LoggingService.DeleteLog"
     * </pre>
     *
     * <code>optional string method_name = 8;</code>
     */
    public Builder setMethodName(
        java.lang.String value) {
      copyOnWrite();
      instance.setMethodName(value);
      return this;
    }
    /**
     * <pre>
     * The name of the service method or operation.
     * For API calls, this should be the name of the API method.
     * For example,
     *     "google.datastore.v1.Datastore.RunQuery"
     *     "google.logging.v1.LoggingService.DeleteLog"
     * </pre>
     *
     * <code>optional string method_name = 8;</code>
     */
    public Builder clearMethodName() {
      copyOnWrite();
      instance.clearMethodName();
      return this;
    }
    /**
     * <pre>
     * The name of the service method or operation.
     * For API calls, this should be the name of the API method.
     * For example,
     *     "google.datastore.v1.Datastore.RunQuery"
     *     "google.logging.v1.LoggingService.DeleteLog"
     * </pre>
     *
     * <code>optional string method_name = 8;</code>
     */
    public Builder setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMethodNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * The resource or collection that is the target of the operation.
     * The name is a scheme-less URI, not including the API service name.
     * For example:
     *     "shelves/SHELF_ID/books"
     *     "shelves/SHELF_ID/books/BOOK_ID"
     * </pre>
     *
     * <code>optional string resource_name = 11;</code>
     */
    public java.lang.String getResourceName() {
      return instance.getResourceName();
    }
    /**
     * <pre>
     * The resource or collection that is the target of the operation.
     * The name is a scheme-less URI, not including the API service name.
     * For example:
     *     "shelves/SHELF_ID/books"
     *     "shelves/SHELF_ID/books/BOOK_ID"
     * </pre>
     *
     * <code>optional string resource_name = 11;</code>
     */
    public com.google.protobuf.ByteString
        getResourceNameBytes() {
      return instance.getResourceNameBytes();
    }
    /**
     * <pre>
     * The resource or collection that is the target of the operation.
     * The name is a scheme-less URI, not including the API service name.
     * For example:
     *     "shelves/SHELF_ID/books"
     *     "shelves/SHELF_ID/books/BOOK_ID"
     * </pre>
     *
     * <code>optional string resource_name = 11;</code>
     */
    public Builder setResourceName(
        java.lang.String value) {
      copyOnWrite();
      instance.setResourceName(value);
      return this;
    }
    /**
     * <pre>
     * The resource or collection that is the target of the operation.
     * The name is a scheme-less URI, not including the API service name.
     * For example:
     *     "shelves/SHELF_ID/books"
     *     "shelves/SHELF_ID/books/BOOK_ID"
     * </pre>
     *
     * <code>optional string resource_name = 11;</code>
     */
    public Builder clearResourceName() {
      copyOnWrite();
      instance.clearResourceName();
      return this;
    }
    /**
     * <pre>
     * The resource or collection that is the target of the operation.
     * The name is a scheme-less URI, not including the API service name.
     * For example:
     *     "shelves/SHELF_ID/books"
     *     "shelves/SHELF_ID/books/BOOK_ID"
     * </pre>
     *
     * <code>optional string resource_name = 11;</code>
     */
    public Builder setResourceNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResourceNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * The number of items returned from a List or Query API method,
     * if applicable.
     * </pre>
     *
     * <code>optional int64 num_response_items = 12;</code>
     */
    public long getNumResponseItems() {
      return instance.getNumResponseItems();
    }
    /**
     * <pre>
     * The number of items returned from a List or Query API method,
     * if applicable.
     * </pre>
     *
     * <code>optional int64 num_response_items = 12;</code>
     */
    public Builder setNumResponseItems(long value) {
      copyOnWrite();
      instance.setNumResponseItems(value);
      return this;
    }
    /**
     * <pre>
     * The number of items returned from a List or Query API method,
     * if applicable.
     * </pre>
     *
     * <code>optional int64 num_response_items = 12;</code>
     */
    public Builder clearNumResponseItems() {
      copyOnWrite();
      instance.clearNumResponseItems();
      return this;
    }

    /**
     * <pre>
     * The status of the overall operation.
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public boolean hasStatus() {
      return instance.hasStatus();
    }
    /**
     * <pre>
     * The status of the overall operation.
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public com.google.rpc.Status getStatus() {
      return instance.getStatus();
    }
    /**
     * <pre>
     * The status of the overall operation.
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public Builder setStatus(com.google.rpc.Status value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
      }
    /**
     * <pre>
     * The status of the overall operation.
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public Builder setStatus(
        com.google.rpc.Status.Builder builderForValue) {
      copyOnWrite();
      instance.setStatus(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The status of the overall operation.
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public Builder mergeStatus(com.google.rpc.Status value) {
      copyOnWrite();
      instance.mergeStatus(value);
      return this;
    }
    /**
     * <pre>
     * The status of the overall operation.
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public Builder clearStatus() {  copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <pre>
     * Authentication information.
     * </pre>
     *
     * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
     */
    public boolean hasAuthenticationInfo() {
      return instance.hasAuthenticationInfo();
    }
    /**
     * <pre>
     * Authentication information.
     * </pre>
     *
     * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
     */
    public com.google.cloud.audit.AuthenticationInfo getAuthenticationInfo() {
      return instance.getAuthenticationInfo();
    }
    /**
     * <pre>
     * Authentication information.
     * </pre>
     *
     * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
     */
    public Builder setAuthenticationInfo(com.google.cloud.audit.AuthenticationInfo value) {
      copyOnWrite();
      instance.setAuthenticationInfo(value);
      return this;
      }
    /**
     * <pre>
     * Authentication information.
     * </pre>
     *
     * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
     */
    public Builder setAuthenticationInfo(
        com.google.cloud.audit.AuthenticationInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setAuthenticationInfo(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Authentication information.
     * </pre>
     *
     * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
     */
    public Builder mergeAuthenticationInfo(com.google.cloud.audit.AuthenticationInfo value) {
      copyOnWrite();
      instance.mergeAuthenticationInfo(value);
      return this;
    }
    /**
     * <pre>
     * Authentication information.
     * </pre>
     *
     * <code>optional .google.cloud.audit.AuthenticationInfo authentication_info = 3;</code>
     */
    public Builder clearAuthenticationInfo() {  copyOnWrite();
      instance.clearAuthenticationInfo();
      return this;
    }

    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public java.util.List<com.google.cloud.audit.AuthorizationInfo> getAuthorizationInfoList() {
      return java.util.Collections.unmodifiableList(
          instance.getAuthorizationInfoList());
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public int getAuthorizationInfoCount() {
      return instance.getAuthorizationInfoCount();
    }/**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public com.google.cloud.audit.AuthorizationInfo getAuthorizationInfo(int index) {
      return instance.getAuthorizationInfo(index);
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder setAuthorizationInfo(
        int index, com.google.cloud.audit.AuthorizationInfo value) {
      copyOnWrite();
      instance.setAuthorizationInfo(index, value);
      return this;
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder setAuthorizationInfo(
        int index, com.google.cloud.audit.AuthorizationInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setAuthorizationInfo(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder addAuthorizationInfo(com.google.cloud.audit.AuthorizationInfo value) {
      copyOnWrite();
      instance.addAuthorizationInfo(value);
      return this;
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder addAuthorizationInfo(
        int index, com.google.cloud.audit.AuthorizationInfo value) {
      copyOnWrite();
      instance.addAuthorizationInfo(index, value);
      return this;
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder addAuthorizationInfo(
        com.google.cloud.audit.AuthorizationInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addAuthorizationInfo(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder addAuthorizationInfo(
        int index, com.google.cloud.audit.AuthorizationInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addAuthorizationInfo(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder addAllAuthorizationInfo(
        java.lang.Iterable<? extends com.google.cloud.audit.AuthorizationInfo> values) {
      copyOnWrite();
      instance.addAllAuthorizationInfo(values);
      return this;
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder clearAuthorizationInfo() {
      copyOnWrite();
      instance.clearAuthorizationInfo();
      return this;
    }
    /**
     * <pre>
     * Authorization information. If there are multiple
     * resources or permissions involved, then there is
     * one AuthorizationInfo element for each {resource, permission} tuple.
     * </pre>
     *
     * <code>repeated .google.cloud.audit.AuthorizationInfo authorization_info = 9;</code>
     */
    public Builder removeAuthorizationInfo(int index) {
      copyOnWrite();
      instance.removeAuthorizationInfo(index);
      return this;
    }

    /**
     * <pre>
     * Metadata about the operation.
     * </pre>
     *
     * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
     */
    public boolean hasRequestMetadata() {
      return instance.hasRequestMetadata();
    }
    /**
     * <pre>
     * Metadata about the operation.
     * </pre>
     *
     * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
     */
    public com.google.cloud.audit.RequestMetadata getRequestMetadata() {
      return instance.getRequestMetadata();
    }
    /**
     * <pre>
     * Metadata about the operation.
     * </pre>
     *
     * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
     */
    public Builder setRequestMetadata(com.google.cloud.audit.RequestMetadata value) {
      copyOnWrite();
      instance.setRequestMetadata(value);
      return this;
      }
    /**
     * <pre>
     * Metadata about the operation.
     * </pre>
     *
     * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
     */
    public Builder setRequestMetadata(
        com.google.cloud.audit.RequestMetadata.Builder builderForValue) {
      copyOnWrite();
      instance.setRequestMetadata(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Metadata about the operation.
     * </pre>
     *
     * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
     */
    public Builder mergeRequestMetadata(com.google.cloud.audit.RequestMetadata value) {
      copyOnWrite();
      instance.mergeRequestMetadata(value);
      return this;
    }
    /**
     * <pre>
     * Metadata about the operation.
     * </pre>
     *
     * <code>optional .google.cloud.audit.RequestMetadata request_metadata = 4;</code>
     */
    public Builder clearRequestMetadata() {  copyOnWrite();
      instance.clearRequestMetadata();
      return this;
    }

    /**
     * <pre>
     * The operation request. This may not include all request parameters,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct request = 16;</code>
     */
    public boolean hasRequest() {
      return instance.hasRequest();
    }
    /**
     * <pre>
     * The operation request. This may not include all request parameters,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct request = 16;</code>
     */
    public com.google.protobuf.Struct getRequest() {
      return instance.getRequest();
    }
    /**
     * <pre>
     * The operation request. This may not include all request parameters,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct request = 16;</code>
     */
    public Builder setRequest(com.google.protobuf.Struct value) {
      copyOnWrite();
      instance.setRequest(value);
      return this;
      }
    /**
     * <pre>
     * The operation request. This may not include all request parameters,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct request = 16;</code>
     */
    public Builder setRequest(
        com.google.protobuf.Struct.Builder builderForValue) {
      copyOnWrite();
      instance.setRequest(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The operation request. This may not include all request parameters,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct request = 16;</code>
     */
    public Builder mergeRequest(com.google.protobuf.Struct value) {
      copyOnWrite();
      instance.mergeRequest(value);
      return this;
    }
    /**
     * <pre>
     * The operation request. This may not include all request parameters,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct request = 16;</code>
     */
    public Builder clearRequest() {  copyOnWrite();
      instance.clearRequest();
      return this;
    }

    /**
     * <pre>
     * The operation response. This may not include all response elements,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct response = 17;</code>
     */
    public boolean hasResponse() {
      return instance.hasResponse();
    }
    /**
     * <pre>
     * The operation response. This may not include all response elements,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct response = 17;</code>
     */
    public com.google.protobuf.Struct getResponse() {
      return instance.getResponse();
    }
    /**
     * <pre>
     * The operation response. This may not include all response elements,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct response = 17;</code>
     */
    public Builder setResponse(com.google.protobuf.Struct value) {
      copyOnWrite();
      instance.setResponse(value);
      return this;
      }
    /**
     * <pre>
     * The operation response. This may not include all response elements,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct response = 17;</code>
     */
    public Builder setResponse(
        com.google.protobuf.Struct.Builder builderForValue) {
      copyOnWrite();
      instance.setResponse(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The operation response. This may not include all response elements,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct response = 17;</code>
     */
    public Builder mergeResponse(com.google.protobuf.Struct value) {
      copyOnWrite();
      instance.mergeResponse(value);
      return this;
    }
    /**
     * <pre>
     * The operation response. This may not include all response elements,
     * such as those that are too large, privacy-sensitive, or duplicated
     * elsewhere in the log record.
     * It should never include user-generated data, such as file contents.
     * When the JSON object represented here has a proto equivalent, the proto
     * name will be indicated in the `&#64;type` property.
     * </pre>
     *
     * <code>optional .google.protobuf.Struct response = 17;</code>
     */
    public Builder clearResponse() {  copyOnWrite();
      instance.clearResponse();
      return this;
    }

    /**
     * <pre>
     * Other service-specific data about the request, response, and other
     * activities.
     * </pre>
     *
     * <code>optional .google.protobuf.Any service_data = 15;</code>
     */
    public boolean hasServiceData() {
      return instance.hasServiceData();
    }
    /**
     * <pre>
     * Other service-specific data about the request, response, and other
     * activities.
     * </pre>
     *
     * <code>optional .google.protobuf.Any service_data = 15;</code>
     */
    public com.google.protobuf.Any getServiceData() {
      return instance.getServiceData();
    }
    /**
     * <pre>
     * Other service-specific data about the request, response, and other
     * activities.
     * </pre>
     *
     * <code>optional .google.protobuf.Any service_data = 15;</code>
     */
    public Builder setServiceData(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.setServiceData(value);
      return this;
      }
    /**
     * <pre>
     * Other service-specific data about the request, response, and other
     * activities.
     * </pre>
     *
     * <code>optional .google.protobuf.Any service_data = 15;</code>
     */
    public Builder setServiceData(
        com.google.protobuf.Any.Builder builderForValue) {
      copyOnWrite();
      instance.setServiceData(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Other service-specific data about the request, response, and other
     * activities.
     * </pre>
     *
     * <code>optional .google.protobuf.Any service_data = 15;</code>
     */
    public Builder mergeServiceData(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.mergeServiceData(value);
      return this;
    }
    /**
     * <pre>
     * Other service-specific data about the request, response, and other
     * activities.
     * </pre>
     *
     * <code>optional .google.protobuf.Any service_data = 15;</code>
     */
    public Builder clearServiceData() {  copyOnWrite();
      instance.clearServiceData();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.audit.AuditLog)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.cloud.audit.AuditLog();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        authorizationInfo_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.cloud.audit.AuditLog other = (com.google.cloud.audit.AuditLog) arg1;
        serviceName_ = visitor.visitString(!serviceName_.isEmpty(), serviceName_,
            !other.serviceName_.isEmpty(), other.serviceName_);
        methodName_ = visitor.visitString(!methodName_.isEmpty(), methodName_,
            !other.methodName_.isEmpty(), other.methodName_);
        resourceName_ = visitor.visitString(!resourceName_.isEmpty(), resourceName_,
            !other.resourceName_.isEmpty(), other.resourceName_);
        numResponseItems_ = visitor.visitLong(numResponseItems_ != 0L, numResponseItems_,
            other.numResponseItems_ != 0L, other.numResponseItems_);
        status_ = visitor.visitMessage(status_, other.status_);
        authenticationInfo_ = visitor.visitMessage(authenticationInfo_, other.authenticationInfo_);
        authorizationInfo_= visitor.visitList(authorizationInfo_, other.authorizationInfo_);
        requestMetadata_ = visitor.visitMessage(requestMetadata_, other.requestMetadata_);
        request_ = visitor.visitMessage(request_, other.request_);
        response_ = visitor.visitMessage(response_, other.response_);
        serviceData_ = visitor.visitMessage(serviceData_, other.serviceData_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 18: {
                com.google.rpc.Status.Builder subBuilder = null;
                if (status_ != null) {
                  subBuilder = status_.toBuilder();
                }
                status_ = input.readMessage(com.google.rpc.Status.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(status_);
                  status_ = subBuilder.buildPartial();
                }

                break;
              }
              case 26: {
                com.google.cloud.audit.AuthenticationInfo.Builder subBuilder = null;
                if (authenticationInfo_ != null) {
                  subBuilder = authenticationInfo_.toBuilder();
                }
                authenticationInfo_ = input.readMessage(com.google.cloud.audit.AuthenticationInfo.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(authenticationInfo_);
                  authenticationInfo_ = subBuilder.buildPartial();
                }

                break;
              }
              case 34: {
                com.google.cloud.audit.RequestMetadata.Builder subBuilder = null;
                if (requestMetadata_ != null) {
                  subBuilder = requestMetadata_.toBuilder();
                }
                requestMetadata_ = input.readMessage(com.google.cloud.audit.RequestMetadata.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(requestMetadata_);
                  requestMetadata_ = subBuilder.buildPartial();
                }

                break;
              }
              case 58: {
                String s = input.readStringRequireUtf8();

                serviceName_ = s;
                break;
              }
              case 66: {
                String s = input.readStringRequireUtf8();

                methodName_ = s;
                break;
              }
              case 74: {
                if (!authorizationInfo_.isModifiable()) {
                  authorizationInfo_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(authorizationInfo_);
                }
                authorizationInfo_.add(
                    input.readMessage(com.google.cloud.audit.AuthorizationInfo.parser(), extensionRegistry));
                break;
              }
              case 90: {
                String s = input.readStringRequireUtf8();

                resourceName_ = s;
                break;
              }
              case 96: {

                numResponseItems_ = input.readInt64();
                break;
              }
              case 122: {
                com.google.protobuf.Any.Builder subBuilder = null;
                if (serviceData_ != null) {
                  subBuilder = serviceData_.toBuilder();
                }
                serviceData_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(serviceData_);
                  serviceData_ = subBuilder.buildPartial();
                }

                break;
              }
              case 130: {
                com.google.protobuf.Struct.Builder subBuilder = null;
                if (request_ != null) {
                  subBuilder = request_.toBuilder();
                }
                request_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(request_);
                  request_ = subBuilder.buildPartial();
                }

                break;
              }
              case 138: {
                com.google.protobuf.Struct.Builder subBuilder = null;
                if (response_ != null) {
                  subBuilder = response_.toBuilder();
                }
                response_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(response_);
                  response_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.cloud.audit.AuditLog.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.cloud.audit.AuditLog)
  private static final com.google.cloud.audit.AuditLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AuditLog();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.cloud.audit.AuditLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AuditLog> PARSER;

  public static com.google.protobuf.Parser<AuditLog> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

