// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/audit/audit_log.proto

package com.google.cloud.audit;

/**
 * <pre>
 * Authorization information for the operation.
 * </pre>
 *
 * Protobuf type {@code google.cloud.audit.AuthorizationInfo}
 */
public  final class AuthorizationInfo extends
    com.google.protobuf.GeneratedMessageLite<
        AuthorizationInfo, AuthorizationInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:google.cloud.audit.AuthorizationInfo)
    AuthorizationInfoOrBuilder {
  private AuthorizationInfo() {
    resource_ = "";
    permission_ = "";
  }
  public static final int RESOURCE_FIELD_NUMBER = 1;
  private java.lang.String resource_;
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>optional string resource = 1;</code>
   */
  public java.lang.String getResource() {
    return resource_;
  }
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>optional string resource = 1;</code>
   */
  public com.google.protobuf.ByteString
      getResourceBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(resource_);
  }
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>optional string resource = 1;</code>
   */
  private void setResource(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    resource_ = value;
  }
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>optional string resource = 1;</code>
   */
  private void clearResource() {
    
    resource_ = getDefaultInstance().getResource();
  }
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>optional string resource = 1;</code>
   */
  private void setResourceBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    resource_ = value.toStringUtf8();
  }

  public static final int PERMISSION_FIELD_NUMBER = 2;
  private java.lang.String permission_;
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>optional string permission = 2;</code>
   */
  public java.lang.String getPermission() {
    return permission_;
  }
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>optional string permission = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPermissionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(permission_);
  }
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>optional string permission = 2;</code>
   */
  private void setPermission(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    permission_ = value;
  }
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>optional string permission = 2;</code>
   */
  private void clearPermission() {
    
    permission_ = getDefaultInstance().getPermission();
  }
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>optional string permission = 2;</code>
   */
  private void setPermissionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    permission_ = value.toStringUtf8();
  }

  public static final int GRANTED_FIELD_NUMBER = 3;
  private boolean granted_;
  /**
   * <pre>
   * Whether or not authorization for `resource` and `permission`
   * was granted.
   * </pre>
   *
   * <code>optional bool granted = 3;</code>
   */
  public boolean getGranted() {
    return granted_;
  }
  /**
   * <pre>
   * Whether or not authorization for `resource` and `permission`
   * was granted.
   * </pre>
   *
   * <code>optional bool granted = 3;</code>
   */
  private void setGranted(boolean value) {
    
    granted_ = value;
  }
  /**
   * <pre>
   * Whether or not authorization for `resource` and `permission`
   * was granted.
   * </pre>
   *
   * <code>optional bool granted = 3;</code>
   */
  private void clearGranted() {
    
    granted_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!resource_.isEmpty()) {
      output.writeString(1, getResource());
    }
    if (!permission_.isEmpty()) {
      output.writeString(2, getPermission());
    }
    if (granted_ != false) {
      output.writeBool(3, granted_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!resource_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getResource());
    }
    if (!permission_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getPermission());
    }
    if (granted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, granted_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.cloud.audit.AuthorizationInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuthorizationInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.audit.AuthorizationInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Authorization information for the operation.
   * </pre>
   *
   * Protobuf type {@code google.cloud.audit.AuthorizationInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.cloud.audit.AuthorizationInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.audit.AuthorizationInfo)
      com.google.cloud.audit.AuthorizationInfoOrBuilder {
    // Construct using com.google.cloud.audit.AuthorizationInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>optional string resource = 1;</code>
     */
    public java.lang.String getResource() {
      return instance.getResource();
    }
    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>optional string resource = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResourceBytes() {
      return instance.getResourceBytes();
    }
    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>optional string resource = 1;</code>
     */
    public Builder setResource(
        java.lang.String value) {
      copyOnWrite();
      instance.setResource(value);
      return this;
    }
    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>optional string resource = 1;</code>
     */
    public Builder clearResource() {
      copyOnWrite();
      instance.clearResource();
      return this;
    }
    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>optional string resource = 1;</code>
     */
    public Builder setResourceBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResourceBytes(value);
      return this;
    }

    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>optional string permission = 2;</code>
     */
    public java.lang.String getPermission() {
      return instance.getPermission();
    }
    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>optional string permission = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPermissionBytes() {
      return instance.getPermissionBytes();
    }
    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>optional string permission = 2;</code>
     */
    public Builder setPermission(
        java.lang.String value) {
      copyOnWrite();
      instance.setPermission(value);
      return this;
    }
    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>optional string permission = 2;</code>
     */
    public Builder clearPermission() {
      copyOnWrite();
      instance.clearPermission();
      return this;
    }
    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>optional string permission = 2;</code>
     */
    public Builder setPermissionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPermissionBytes(value);
      return this;
    }

    /**
     * <pre>
     * Whether or not authorization for `resource` and `permission`
     * was granted.
     * </pre>
     *
     * <code>optional bool granted = 3;</code>
     */
    public boolean getGranted() {
      return instance.getGranted();
    }
    /**
     * <pre>
     * Whether or not authorization for `resource` and `permission`
     * was granted.
     * </pre>
     *
     * <code>optional bool granted = 3;</code>
     */
    public Builder setGranted(boolean value) {
      copyOnWrite();
      instance.setGranted(value);
      return this;
    }
    /**
     * <pre>
     * Whether or not authorization for `resource` and `permission`
     * was granted.
     * </pre>
     *
     * <code>optional bool granted = 3;</code>
     */
    public Builder clearGranted() {
      copyOnWrite();
      instance.clearGranted();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.audit.AuthorizationInfo)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.cloud.audit.AuthorizationInfo();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.cloud.audit.AuthorizationInfo other = (com.google.cloud.audit.AuthorizationInfo) arg1;
        resource_ = visitor.visitString(!resource_.isEmpty(), resource_,
            !other.resource_.isEmpty(), other.resource_);
        permission_ = visitor.visitString(!permission_.isEmpty(), permission_,
            !other.permission_.isEmpty(), other.permission_);
        granted_ = visitor.visitBoolean(granted_ != false, granted_,
            other.granted_ != false, other.granted_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                resource_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                permission_ = s;
                break;
              }
              case 24: {

                granted_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.cloud.audit.AuthorizationInfo.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.cloud.audit.AuthorizationInfo)
  private static final com.google.cloud.audit.AuthorizationInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AuthorizationInfo();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.cloud.audit.AuthorizationInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AuthorizationInfo> PARSER;

  public static com.google.protobuf.Parser<AuthorizationInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

