// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/audit/audit_log.proto

package com.google.cloud.audit;

/**
 * <pre>
 * Authentication information for the operation.
 * </pre>
 *
 * Protobuf type {@code google.cloud.audit.AuthenticationInfo}
 */
public  final class AuthenticationInfo extends
    com.google.protobuf.GeneratedMessageLite<
        AuthenticationInfo, AuthenticationInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:google.cloud.audit.AuthenticationInfo)
    AuthenticationInfoOrBuilder {
  private AuthenticationInfo() {
    principalEmail_ = "";
  }
  public static final int PRINCIPAL_EMAIL_FIELD_NUMBER = 1;
  private java.lang.String principalEmail_;
  /**
   * <pre>
   * The email address of the authenticated user making the request.
   * </pre>
   *
   * <code>optional string principal_email = 1;</code>
   */
  public java.lang.String getPrincipalEmail() {
    return principalEmail_;
  }
  /**
   * <pre>
   * The email address of the authenticated user making the request.
   * </pre>
   *
   * <code>optional string principal_email = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPrincipalEmailBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(principalEmail_);
  }
  /**
   * <pre>
   * The email address of the authenticated user making the request.
   * </pre>
   *
   * <code>optional string principal_email = 1;</code>
   */
  private void setPrincipalEmail(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    principalEmail_ = value;
  }
  /**
   * <pre>
   * The email address of the authenticated user making the request.
   * </pre>
   *
   * <code>optional string principal_email = 1;</code>
   */
  private void clearPrincipalEmail() {
    
    principalEmail_ = getDefaultInstance().getPrincipalEmail();
  }
  /**
   * <pre>
   * The email address of the authenticated user making the request.
   * </pre>
   *
   * <code>optional string principal_email = 1;</code>
   */
  private void setPrincipalEmailBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    principalEmail_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!principalEmail_.isEmpty()) {
      output.writeString(1, getPrincipalEmail());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!principalEmail_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getPrincipalEmail());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.cloud.audit.AuthenticationInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.cloud.audit.AuthenticationInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.audit.AuthenticationInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Authentication information for the operation.
   * </pre>
   *
   * Protobuf type {@code google.cloud.audit.AuthenticationInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.cloud.audit.AuthenticationInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.audit.AuthenticationInfo)
      com.google.cloud.audit.AuthenticationInfoOrBuilder {
    // Construct using com.google.cloud.audit.AuthenticationInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>optional string principal_email = 1;</code>
     */
    public java.lang.String getPrincipalEmail() {
      return instance.getPrincipalEmail();
    }
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>optional string principal_email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPrincipalEmailBytes() {
      return instance.getPrincipalEmailBytes();
    }
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>optional string principal_email = 1;</code>
     */
    public Builder setPrincipalEmail(
        java.lang.String value) {
      copyOnWrite();
      instance.setPrincipalEmail(value);
      return this;
    }
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>optional string principal_email = 1;</code>
     */
    public Builder clearPrincipalEmail() {
      copyOnWrite();
      instance.clearPrincipalEmail();
      return this;
    }
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>optional string principal_email = 1;</code>
     */
    public Builder setPrincipalEmailBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPrincipalEmailBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.audit.AuthenticationInfo)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.cloud.audit.AuthenticationInfo();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.cloud.audit.AuthenticationInfo other = (com.google.cloud.audit.AuthenticationInfo) arg1;
        principalEmail_ = visitor.visitString(!principalEmail_.isEmpty(), principalEmail_,
            !other.principalEmail_.isEmpty(), other.principalEmail_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                principalEmail_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.cloud.audit.AuthenticationInfo.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.cloud.audit.AuthenticationInfo)
  private static final com.google.cloud.audit.AuthenticationInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AuthenticationInfo();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.cloud.audit.AuthenticationInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AuthenticationInfo> PARSER;

  public static com.google.protobuf.Parser<AuthenticationInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

