// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/experimental/authorization_config.proto

package com.google.api;

/**
 * <pre>
 * Configuration of authorization.
 * This section determines the authorization provider, if unspecified, then no
 * authorization check will be done.
 * Example:
 *     experimental:
 *       authorization:
 *         provider: firebaserules.googleapis.com
 * </pre>
 *
 * Protobuf type {@code google.api.AuthorizationConfig}
 */
public  final class AuthorizationConfig extends
    com.google.protobuf.GeneratedMessageLite<
        AuthorizationConfig, AuthorizationConfig.Builder> implements
    // @@protoc_insertion_point(message_implements:google.api.AuthorizationConfig)
    AuthorizationConfigOrBuilder {
  private AuthorizationConfig() {
    provider_ = "";
  }
  public static final int PROVIDER_FIELD_NUMBER = 1;
  private java.lang.String provider_;
  /**
   * <pre>
   * The name of the authorization provider, such as
   * firebaserules.googleapis.com.
   * </pre>
   *
   * <code>optional string provider = 1;</code>
   */
  public java.lang.String getProvider() {
    return provider_;
  }
  /**
   * <pre>
   * The name of the authorization provider, such as
   * firebaserules.googleapis.com.
   * </pre>
   *
   * <code>optional string provider = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProviderBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(provider_);
  }
  /**
   * <pre>
   * The name of the authorization provider, such as
   * firebaserules.googleapis.com.
   * </pre>
   *
   * <code>optional string provider = 1;</code>
   */
  private void setProvider(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    provider_ = value;
  }
  /**
   * <pre>
   * The name of the authorization provider, such as
   * firebaserules.googleapis.com.
   * </pre>
   *
   * <code>optional string provider = 1;</code>
   */
  private void clearProvider() {
    
    provider_ = getDefaultInstance().getProvider();
  }
  /**
   * <pre>
   * The name of the authorization provider, such as
   * firebaserules.googleapis.com.
   * </pre>
   *
   * <code>optional string provider = 1;</code>
   */
  private void setProviderBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    provider_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!provider_.isEmpty()) {
      output.writeString(1, getProvider());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!provider_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getProvider());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.api.AuthorizationConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.AuthorizationConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.AuthorizationConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.AuthorizationConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.AuthorizationConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.AuthorizationConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.AuthorizationConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.api.AuthorizationConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.AuthorizationConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.AuthorizationConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.AuthorizationConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Configuration of authorization.
   * This section determines the authorization provider, if unspecified, then no
   * authorization check will be done.
   * Example:
   *     experimental:
   *       authorization:
   *         provider: firebaserules.googleapis.com
   * </pre>
   *
   * Protobuf type {@code google.api.AuthorizationConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.api.AuthorizationConfig, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.AuthorizationConfig)
      com.google.api.AuthorizationConfigOrBuilder {
    // Construct using com.google.api.AuthorizationConfig.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The name of the authorization provider, such as
     * firebaserules.googleapis.com.
     * </pre>
     *
     * <code>optional string provider = 1;</code>
     */
    public java.lang.String getProvider() {
      return instance.getProvider();
    }
    /**
     * <pre>
     * The name of the authorization provider, such as
     * firebaserules.googleapis.com.
     * </pre>
     *
     * <code>optional string provider = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProviderBytes() {
      return instance.getProviderBytes();
    }
    /**
     * <pre>
     * The name of the authorization provider, such as
     * firebaserules.googleapis.com.
     * </pre>
     *
     * <code>optional string provider = 1;</code>
     */
    public Builder setProvider(
        java.lang.String value) {
      copyOnWrite();
      instance.setProvider(value);
      return this;
    }
    /**
     * <pre>
     * The name of the authorization provider, such as
     * firebaserules.googleapis.com.
     * </pre>
     *
     * <code>optional string provider = 1;</code>
     */
    public Builder clearProvider() {
      copyOnWrite();
      instance.clearProvider();
      return this;
    }
    /**
     * <pre>
     * The name of the authorization provider, such as
     * firebaserules.googleapis.com.
     * </pre>
     *
     * <code>optional string provider = 1;</code>
     */
    public Builder setProviderBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProviderBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.api.AuthorizationConfig)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.api.AuthorizationConfig();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.api.AuthorizationConfig other = (com.google.api.AuthorizationConfig) arg1;
        provider_ = visitor.visitString(!provider_.isEmpty(), provider_,
            !other.provider_.isEmpty(), other.provider_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                provider_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.api.AuthorizationConfig.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.api.AuthorizationConfig)
  private static final com.google.api.AuthorizationConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AuthorizationConfig();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.api.AuthorizationConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AuthorizationConfig> PARSER;

  public static com.google.protobuf.Parser<AuthorizationConfig> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

