// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/billing.proto

package com.google.api;

/**
 * <pre>
 * Billing related configuration of the service.
 * The following example shows how to configure monitored resources and metrics
 * for billing:
 *     monitored_resources:
 *     - type: library.googleapis.com/branch
 *       labels:
 *       - key: /city
 *         description: The city where the library branch is located in.
 *       - key: /name
 *         description: The name of the branch.
 *     metrics:
 *     - name: library.googleapis.com/book/borrowed_count
 *       metric_kind: DELTA
 *       value_type: INT64
 *     billing:
 *       consumer_destinations:
 *       - monitored_resource: library.googleapis.com/branch
 *         metrics:
 *         - library.googleapis.com/book/borrowed_count
 * </pre>
 *
 * Protobuf type {@code google.api.Billing}
 */
public  final class Billing extends
    com.google.protobuf.GeneratedMessageLite<
        Billing, Billing.Builder> implements
    // @@protoc_insertion_point(message_implements:google.api.Billing)
    BillingOrBuilder {
  private Billing() {
    consumerDestinations_ = emptyProtobufList();
  }
  public interface BillingDestinationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.api.Billing.BillingDestination)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The monitored resource type. The type must be defined in
     * [Service.monitored_resources][google.api.Service.monitored_resources] section.
     * </pre>
     *
     * <code>optional string monitored_resource = 1;</code>
     */
    java.lang.String getMonitoredResource();
    /**
     * <pre>
     * The monitored resource type. The type must be defined in
     * [Service.monitored_resources][google.api.Service.monitored_resources] section.
     * </pre>
     *
     * <code>optional string monitored_resource = 1;</code>
     */
    com.google.protobuf.ByteString
        getMonitoredResourceBytes();

    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    java.util.List<String>
        getMetricsList();
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    int getMetricsCount();
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    java.lang.String getMetrics(int index);
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    com.google.protobuf.ByteString
        getMetricsBytes(int index);
  }
  /**
   * <pre>
   * Configuration of a specific billing destination (Currently only support
   * bill against consumer project).
   * </pre>
   *
   * Protobuf type {@code google.api.Billing.BillingDestination}
   */
  public  static final class BillingDestination extends
      com.google.protobuf.GeneratedMessageLite<
          BillingDestination, BillingDestination.Builder> implements
      // @@protoc_insertion_point(message_implements:google.api.Billing.BillingDestination)
      BillingDestinationOrBuilder {
    private BillingDestination() {
      monitoredResource_ = "";
      metrics_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    private int bitField0_;
    public static final int MONITORED_RESOURCE_FIELD_NUMBER = 1;
    private java.lang.String monitoredResource_;
    /**
     * <pre>
     * The monitored resource type. The type must be defined in
     * [Service.monitored_resources][google.api.Service.monitored_resources] section.
     * </pre>
     *
     * <code>optional string monitored_resource = 1;</code>
     */
    public java.lang.String getMonitoredResource() {
      return monitoredResource_;
    }
    /**
     * <pre>
     * The monitored resource type. The type must be defined in
     * [Service.monitored_resources][google.api.Service.monitored_resources] section.
     * </pre>
     *
     * <code>optional string monitored_resource = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMonitoredResourceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(monitoredResource_);
    }
    /**
     * <pre>
     * The monitored resource type. The type must be defined in
     * [Service.monitored_resources][google.api.Service.monitored_resources] section.
     * </pre>
     *
     * <code>optional string monitored_resource = 1;</code>
     */
    private void setMonitoredResource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      monitoredResource_ = value;
    }
    /**
     * <pre>
     * The monitored resource type. The type must be defined in
     * [Service.monitored_resources][google.api.Service.monitored_resources] section.
     * </pre>
     *
     * <code>optional string monitored_resource = 1;</code>
     */
    private void clearMonitoredResource() {
      
      monitoredResource_ = getDefaultInstance().getMonitoredResource();
    }
    /**
     * <pre>
     * The monitored resource type. The type must be defined in
     * [Service.monitored_resources][google.api.Service.monitored_resources] section.
     * </pre>
     *
     * <code>optional string monitored_resource = 1;</code>
     */
    private void setMonitoredResourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      monitoredResource_ = value.toStringUtf8();
    }

    public static final int METRICS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<String> metrics_;
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    public java.util.List<String> getMetricsList() {
      return metrics_;
    }
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    public int getMetricsCount() {
      return metrics_.size();
    }
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    public java.lang.String getMetrics(int index) {
      return metrics_.get(index);
    }
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMetricsBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          metrics_.get(index));
    }
    private void ensureMetricsIsMutable() {
      if (!metrics_.isModifiable()) {
        metrics_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(metrics_);
       }
    }
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    private void setMetrics(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMetricsIsMutable();
      metrics_.set(index, value);
    }
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    private void addMetrics(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMetricsIsMutable();
      metrics_.add(value);
    }
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    private void addAllMetrics(
        java.lang.Iterable<java.lang.String> values) {
      ensureMetricsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, metrics_);
    }
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    private void clearMetrics() {
      metrics_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <pre>
     * Names of the metrics to report to this billing destination.
     * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
     * </pre>
     *
     * <code>repeated string metrics = 2;</code>
     */
    private void addMetricsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMetricsIsMutable();
      metrics_.add(value.toStringUtf8());
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!monitoredResource_.isEmpty()) {
        output.writeString(1, getMonitoredResource());
      }
      for (int i = 0; i < metrics_.size(); i++) {
        output.writeString(2, metrics_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!monitoredResource_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMonitoredResource());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < metrics_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(metrics_.get(i));
        }
        size += dataSize;
        size += 1 * getMetricsList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.google.api.Billing.BillingDestination parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.api.Billing.BillingDestination parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.api.Billing.BillingDestination parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.api.Billing.BillingDestination parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.api.Billing.BillingDestination parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.api.Billing.BillingDestination parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.api.Billing.BillingDestination parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.api.Billing.BillingDestination parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.api.Billing.BillingDestination parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.api.Billing.BillingDestination parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.api.Billing.BillingDestination prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Configuration of a specific billing destination (Currently only support
     * bill against consumer project).
     * </pre>
     *
     * Protobuf type {@code google.api.Billing.BillingDestination}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.api.Billing.BillingDestination, Builder> implements
        // @@protoc_insertion_point(builder_implements:google.api.Billing.BillingDestination)
        com.google.api.Billing.BillingDestinationOrBuilder {
      // Construct using com.google.api.Billing.BillingDestination.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The monitored resource type. The type must be defined in
       * [Service.monitored_resources][google.api.Service.monitored_resources] section.
       * </pre>
       *
       * <code>optional string monitored_resource = 1;</code>
       */
      public java.lang.String getMonitoredResource() {
        return instance.getMonitoredResource();
      }
      /**
       * <pre>
       * The monitored resource type. The type must be defined in
       * [Service.monitored_resources][google.api.Service.monitored_resources] section.
       * </pre>
       *
       * <code>optional string monitored_resource = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMonitoredResourceBytes() {
        return instance.getMonitoredResourceBytes();
      }
      /**
       * <pre>
       * The monitored resource type. The type must be defined in
       * [Service.monitored_resources][google.api.Service.monitored_resources] section.
       * </pre>
       *
       * <code>optional string monitored_resource = 1;</code>
       */
      public Builder setMonitoredResource(
          java.lang.String value) {
        copyOnWrite();
        instance.setMonitoredResource(value);
        return this;
      }
      /**
       * <pre>
       * The monitored resource type. The type must be defined in
       * [Service.monitored_resources][google.api.Service.monitored_resources] section.
       * </pre>
       *
       * <code>optional string monitored_resource = 1;</code>
       */
      public Builder clearMonitoredResource() {
        copyOnWrite();
        instance.clearMonitoredResource();
        return this;
      }
      /**
       * <pre>
       * The monitored resource type. The type must be defined in
       * [Service.monitored_resources][google.api.Service.monitored_resources] section.
       * </pre>
       *
       * <code>optional string monitored_resource = 1;</code>
       */
      public Builder setMonitoredResourceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMonitoredResourceBytes(value);
        return this;
      }

      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public java.util.List<String>
          getMetricsList() {
        return java.util.Collections.unmodifiableList(
            instance.getMetricsList());
      }
      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public int getMetricsCount() {
        return instance.getMetricsCount();
      }
      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public java.lang.String getMetrics(int index) {
        return instance.getMetrics(index);
      }
      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMetricsBytes(int index) {
        return instance.getMetricsBytes(index);
      }
      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public Builder setMetrics(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setMetrics(index, value);
        return this;
      }
      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public Builder addMetrics(
          java.lang.String value) {
        copyOnWrite();
        instance.addMetrics(value);
        return this;
      }
      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public Builder addAllMetrics(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllMetrics(values);
        return this;
      }
      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public Builder clearMetrics() {
        copyOnWrite();
        instance.clearMetrics();
        return this;
      }
      /**
       * <pre>
       * Names of the metrics to report to this billing destination.
       * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
       * </pre>
       *
       * <code>repeated string metrics = 2;</code>
       */
      public Builder addMetricsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addMetricsBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:google.api.Billing.BillingDestination)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.api.Billing.BillingDestination();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          metrics_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.google.api.Billing.BillingDestination other = (com.google.api.Billing.BillingDestination) arg1;
          monitoredResource_ = visitor.visitString(!monitoredResource_.isEmpty(), monitoredResource_,
              !other.monitoredResource_.isEmpty(), other.monitoredResource_);
          metrics_= visitor.visitList(metrics_, other.metrics_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  monitoredResource_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();
                  if (!metrics_.isModifiable()) {
                    metrics_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(metrics_);
                  }
                  metrics_.add(s);
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.google.api.Billing.BillingDestination.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:google.api.Billing.BillingDestination)
    private static final com.google.api.Billing.BillingDestination DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BillingDestination();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.google.api.Billing.BillingDestination getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BillingDestination> PARSER;

    public static com.google.protobuf.Parser<BillingDestination> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int CONSUMER_DESTINATIONS_FIELD_NUMBER = 8;
  private com.google.protobuf.Internal.ProtobufList<com.google.api.Billing.BillingDestination> consumerDestinations_;
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  public java.util.List<com.google.api.Billing.BillingDestination> getConsumerDestinationsList() {
    return consumerDestinations_;
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  public java.util.List<? extends com.google.api.Billing.BillingDestinationOrBuilder> 
      getConsumerDestinationsOrBuilderList() {
    return consumerDestinations_;
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  public int getConsumerDestinationsCount() {
    return consumerDestinations_.size();
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  public com.google.api.Billing.BillingDestination getConsumerDestinations(int index) {
    return consumerDestinations_.get(index);
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  public com.google.api.Billing.BillingDestinationOrBuilder getConsumerDestinationsOrBuilder(
      int index) {
    return consumerDestinations_.get(index);
  }
  private void ensureConsumerDestinationsIsMutable() {
    if (!consumerDestinations_.isModifiable()) {
      consumerDestinations_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(consumerDestinations_);
     }
  }

  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void setConsumerDestinations(
      int index, com.google.api.Billing.BillingDestination value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureConsumerDestinationsIsMutable();
    consumerDestinations_.set(index, value);
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void setConsumerDestinations(
      int index, com.google.api.Billing.BillingDestination.Builder builderForValue) {
    ensureConsumerDestinationsIsMutable();
    consumerDestinations_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void addConsumerDestinations(com.google.api.Billing.BillingDestination value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureConsumerDestinationsIsMutable();
    consumerDestinations_.add(value);
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void addConsumerDestinations(
      int index, com.google.api.Billing.BillingDestination value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureConsumerDestinationsIsMutable();
    consumerDestinations_.add(index, value);
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void addConsumerDestinations(
      com.google.api.Billing.BillingDestination.Builder builderForValue) {
    ensureConsumerDestinationsIsMutable();
    consumerDestinations_.add(builderForValue.build());
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void addConsumerDestinations(
      int index, com.google.api.Billing.BillingDestination.Builder builderForValue) {
    ensureConsumerDestinationsIsMutable();
    consumerDestinations_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void addAllConsumerDestinations(
      java.lang.Iterable<? extends com.google.api.Billing.BillingDestination> values) {
    ensureConsumerDestinationsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, consumerDestinations_);
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void clearConsumerDestinations() {
    consumerDestinations_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Billing configurations for sending metrics to the consumer project.
   * There can be multiple consumer destinations per service, each one must have
   * a different monitored resource type. A metric can be used in at most
   * one consumer destination.
   * </pre>
   *
   * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
   */
  private void removeConsumerDestinations(int index) {
    ensureConsumerDestinationsIsMutable();
    consumerDestinations_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < consumerDestinations_.size(); i++) {
      output.writeMessage(8, consumerDestinations_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < consumerDestinations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, consumerDestinations_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.api.Billing parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.Billing parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.Billing parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.Billing parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.Billing parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Billing parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.Billing parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Billing parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.Billing parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Billing parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.Billing prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Billing related configuration of the service.
   * The following example shows how to configure monitored resources and metrics
   * for billing:
   *     monitored_resources:
   *     - type: library.googleapis.com/branch
   *       labels:
   *       - key: /city
   *         description: The city where the library branch is located in.
   *       - key: /name
   *         description: The name of the branch.
   *     metrics:
   *     - name: library.googleapis.com/book/borrowed_count
   *       metric_kind: DELTA
   *       value_type: INT64
   *     billing:
   *       consumer_destinations:
   *       - monitored_resource: library.googleapis.com/branch
   *         metrics:
   *         - library.googleapis.com/book/borrowed_count
   * </pre>
   *
   * Protobuf type {@code google.api.Billing}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.api.Billing, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.Billing)
      com.google.api.BillingOrBuilder {
    // Construct using com.google.api.Billing.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public java.util.List<com.google.api.Billing.BillingDestination> getConsumerDestinationsList() {
      return java.util.Collections.unmodifiableList(
          instance.getConsumerDestinationsList());
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public int getConsumerDestinationsCount() {
      return instance.getConsumerDestinationsCount();
    }/**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public com.google.api.Billing.BillingDestination getConsumerDestinations(int index) {
      return instance.getConsumerDestinations(index);
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder setConsumerDestinations(
        int index, com.google.api.Billing.BillingDestination value) {
      copyOnWrite();
      instance.setConsumerDestinations(index, value);
      return this;
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder setConsumerDestinations(
        int index, com.google.api.Billing.BillingDestination.Builder builderForValue) {
      copyOnWrite();
      instance.setConsumerDestinations(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder addConsumerDestinations(com.google.api.Billing.BillingDestination value) {
      copyOnWrite();
      instance.addConsumerDestinations(value);
      return this;
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder addConsumerDestinations(
        int index, com.google.api.Billing.BillingDestination value) {
      copyOnWrite();
      instance.addConsumerDestinations(index, value);
      return this;
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder addConsumerDestinations(
        com.google.api.Billing.BillingDestination.Builder builderForValue) {
      copyOnWrite();
      instance.addConsumerDestinations(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder addConsumerDestinations(
        int index, com.google.api.Billing.BillingDestination.Builder builderForValue) {
      copyOnWrite();
      instance.addConsumerDestinations(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder addAllConsumerDestinations(
        java.lang.Iterable<? extends com.google.api.Billing.BillingDestination> values) {
      copyOnWrite();
      instance.addAllConsumerDestinations(values);
      return this;
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder clearConsumerDestinations() {
      copyOnWrite();
      instance.clearConsumerDestinations();
      return this;
    }
    /**
     * <pre>
     * Billing configurations for sending metrics to the consumer project.
     * There can be multiple consumer destinations per service, each one must have
     * a different monitored resource type. A metric can be used in at most
     * one consumer destination.
     * </pre>
     *
     * <code>repeated .google.api.Billing.BillingDestination consumer_destinations = 8;</code>
     */
    public Builder removeConsumerDestinations(int index) {
      copyOnWrite();
      instance.removeConsumerDestinations(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.api.Billing)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.api.Billing();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        consumerDestinations_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.api.Billing other = (com.google.api.Billing) arg1;
        consumerDestinations_= visitor.visitList(consumerDestinations_, other.consumerDestinations_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 66: {
                if (!consumerDestinations_.isModifiable()) {
                  consumerDestinations_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(consumerDestinations_);
                }
                consumerDestinations_.add(
                    input.readMessage(com.google.api.Billing.BillingDestination.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.api.Billing.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.api.Billing)
  private static final com.google.api.Billing DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Billing();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.api.Billing getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Billing> PARSER;

  public static com.google.protobuf.Parser<Billing> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

