// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/endpoint.proto

package com.google.api;

/**
 * <pre>
 * `Endpoint` describes a network endpoint that serves a set of APIs.
 * A service may expose any number of endpoints, and all endpoints share the
 * same service configuration, such as quota configuration and monitoring
 * configuration.
 * Example service configuration:
 *     name: library-example.googleapis.com
 *     endpoints:
 *       # Below entry makes 'google.example.library.v1.Library'
 *       # API be served from endpoint address library-example.googleapis.com.
 *       # It also allows HTTP OPTIONS calls to be passed to the backend, for
 *       # it to decide whether the subsequent cross-origin request is
 *       # allowed to proceed.
 *     - name: library-example.googleapis.com
 *       allow_cors: true
 * </pre>
 *
 * Protobuf type {@code google.api.Endpoint}
 */
public  final class Endpoint extends
    com.google.protobuf.GeneratedMessageLite<
        Endpoint, Endpoint.Builder> implements
    // @@protoc_insertion_point(message_implements:google.api.Endpoint)
    EndpointOrBuilder {
  private Endpoint() {
    name_ = "";
    aliases_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    features_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    target_ = "";
  }
  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <pre>
   * The canonical name of this endpoint.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <pre>
   * The canonical name of this endpoint.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <pre>
   * The canonical name of this endpoint.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <pre>
   * The canonical name of this endpoint.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <pre>
   * The canonical name of this endpoint.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int ALIASES_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<String> aliases_;
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  public java.util.List<String> getAliasesList() {
    return aliases_;
  }
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  public int getAliasesCount() {
    return aliases_.size();
  }
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  public java.lang.String getAliases(int index) {
    return aliases_.get(index);
  }
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAliasesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        aliases_.get(index));
  }
  private void ensureAliasesIsMutable() {
    if (!aliases_.isModifiable()) {
      aliases_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(aliases_);
     }
  }
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  private void setAliases(
      int index, java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureAliasesIsMutable();
    aliases_.set(index, value);
  }
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  private void addAliases(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureAliasesIsMutable();
    aliases_.add(value);
  }
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  private void addAllAliases(
      java.lang.Iterable<java.lang.String> values) {
    ensureAliasesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, aliases_);
  }
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  private void clearAliases() {
    aliases_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * DEPRECATED: This field is no longer supported. Instead of using aliases,
   * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
   * aliases.
   * Additional names that this endpoint will be hosted on.
   * </pre>
   *
   * <code>repeated string aliases = 2;</code>
   */
  private void addAliasesBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    ensureAliasesIsMutable();
    aliases_.add(value.toStringUtf8());
  }

  public static final int FEATURES_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<String> features_;
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  public java.util.List<String> getFeaturesList() {
    return features_;
  }
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  public int getFeaturesCount() {
    return features_.size();
  }
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  public java.lang.String getFeatures(int index) {
    return features_.get(index);
  }
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFeaturesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        features_.get(index));
  }
  private void ensureFeaturesIsMutable() {
    if (!features_.isModifiable()) {
      features_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(features_);
     }
  }
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  private void setFeatures(
      int index, java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureFeaturesIsMutable();
    features_.set(index, value);
  }
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  private void addFeatures(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureFeaturesIsMutable();
    features_.add(value);
  }
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  private void addAllFeatures(
      java.lang.Iterable<java.lang.String> values) {
    ensureFeaturesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, features_);
  }
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  private void clearFeatures() {
    features_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * The list of features enabled on this endpoint.
   * </pre>
   *
   * <code>repeated string features = 4;</code>
   */
  private void addFeaturesBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    ensureFeaturesIsMutable();
    features_.add(value.toStringUtf8());
  }

  public static final int TARGET_FIELD_NUMBER = 101;
  private java.lang.String target_;
  /**
   * <pre>
   * The specification of an Internet routable address of API frontend that will
   * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
   * It should be either a valid IPv4 address or a fully-qualified domain name.
   * For example, "8.8.8.8" or "myservice.appspot.com".
   * </pre>
   *
   * <code>optional string target = 101;</code>
   */
  public java.lang.String getTarget() {
    return target_;
  }
  /**
   * <pre>
   * The specification of an Internet routable address of API frontend that will
   * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
   * It should be either a valid IPv4 address or a fully-qualified domain name.
   * For example, "8.8.8.8" or "myservice.appspot.com".
   * </pre>
   *
   * <code>optional string target = 101;</code>
   */
  public com.google.protobuf.ByteString
      getTargetBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(target_);
  }
  /**
   * <pre>
   * The specification of an Internet routable address of API frontend that will
   * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
   * It should be either a valid IPv4 address or a fully-qualified domain name.
   * For example, "8.8.8.8" or "myservice.appspot.com".
   * </pre>
   *
   * <code>optional string target = 101;</code>
   */
  private void setTarget(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    target_ = value;
  }
  /**
   * <pre>
   * The specification of an Internet routable address of API frontend that will
   * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
   * It should be either a valid IPv4 address or a fully-qualified domain name.
   * For example, "8.8.8.8" or "myservice.appspot.com".
   * </pre>
   *
   * <code>optional string target = 101;</code>
   */
  private void clearTarget() {
    
    target_ = getDefaultInstance().getTarget();
  }
  /**
   * <pre>
   * The specification of an Internet routable address of API frontend that will
   * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
   * It should be either a valid IPv4 address or a fully-qualified domain name.
   * For example, "8.8.8.8" or "myservice.appspot.com".
   * </pre>
   *
   * <code>optional string target = 101;</code>
   */
  private void setTargetBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    target_ = value.toStringUtf8();
  }

  public static final int ALLOW_CORS_FIELD_NUMBER = 5;
  private boolean allowCors_;
  /**
   * <pre>
   * Allowing
   * [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), aka
   * cross-domain traffic, would allow the backends served from this endpoint to
   * receive and respond to HTTP OPTIONS requests. The response will be used by
   * the browser to determine whether the subsequent cross-origin request is
   * allowed to proceed.
   * </pre>
   *
   * <code>optional bool allow_cors = 5;</code>
   */
  public boolean getAllowCors() {
    return allowCors_;
  }
  /**
   * <pre>
   * Allowing
   * [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), aka
   * cross-domain traffic, would allow the backends served from this endpoint to
   * receive and respond to HTTP OPTIONS requests. The response will be used by
   * the browser to determine whether the subsequent cross-origin request is
   * allowed to proceed.
   * </pre>
   *
   * <code>optional bool allow_cors = 5;</code>
   */
  private void setAllowCors(boolean value) {
    
    allowCors_ = value;
  }
  /**
   * <pre>
   * Allowing
   * [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), aka
   * cross-domain traffic, would allow the backends served from this endpoint to
   * receive and respond to HTTP OPTIONS requests. The response will be used by
   * the browser to determine whether the subsequent cross-origin request is
   * allowed to proceed.
   * </pre>
   *
   * <code>optional bool allow_cors = 5;</code>
   */
  private void clearAllowCors() {
    
    allowCors_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!name_.isEmpty()) {
      output.writeString(1, getName());
    }
    for (int i = 0; i < aliases_.size(); i++) {
      output.writeString(2, aliases_.get(i));
    }
    for (int i = 0; i < features_.size(); i++) {
      output.writeString(4, features_.get(i));
    }
    if (allowCors_ != false) {
      output.writeBool(5, allowCors_);
    }
    if (!target_.isEmpty()) {
      output.writeString(101, getTarget());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getName());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < aliases_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeStringSizeNoTag(aliases_.get(i));
      }
      size += dataSize;
      size += 1 * getAliasesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < features_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeStringSizeNoTag(features_.get(i));
      }
      size += dataSize;
      size += 1 * getFeaturesList().size();
    }
    if (allowCors_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, allowCors_);
    }
    if (!target_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(101, getTarget());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.api.Endpoint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.Endpoint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.Endpoint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.Endpoint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.Endpoint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Endpoint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.Endpoint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Endpoint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.Endpoint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Endpoint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.Endpoint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * `Endpoint` describes a network endpoint that serves a set of APIs.
   * A service may expose any number of endpoints, and all endpoints share the
   * same service configuration, such as quota configuration and monitoring
   * configuration.
   * Example service configuration:
   *     name: library-example.googleapis.com
   *     endpoints:
   *       # Below entry makes 'google.example.library.v1.Library'
   *       # API be served from endpoint address library-example.googleapis.com.
   *       # It also allows HTTP OPTIONS calls to be passed to the backend, for
   *       # it to decide whether the subsequent cross-origin request is
   *       # allowed to proceed.
   *     - name: library-example.googleapis.com
   *       allow_cors: true
   * </pre>
   *
   * Protobuf type {@code google.api.Endpoint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.api.Endpoint, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.Endpoint)
      com.google.api.EndpointOrBuilder {
    // Construct using com.google.api.Endpoint.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The canonical name of this endpoint.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <pre>
     * The canonical name of this endpoint.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <pre>
     * The canonical name of this endpoint.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <pre>
     * The canonical name of this endpoint.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <pre>
     * The canonical name of this endpoint.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public java.util.List<String>
        getAliasesList() {
      return java.util.Collections.unmodifiableList(
          instance.getAliasesList());
    }
    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public int getAliasesCount() {
      return instance.getAliasesCount();
    }
    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public java.lang.String getAliases(int index) {
      return instance.getAliases(index);
    }
    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAliasesBytes(int index) {
      return instance.getAliasesBytes(index);
    }
    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public Builder setAliases(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setAliases(index, value);
      return this;
    }
    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public Builder addAliases(
        java.lang.String value) {
      copyOnWrite();
      instance.addAliases(value);
      return this;
    }
    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public Builder addAllAliases(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllAliases(values);
      return this;
    }
    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public Builder clearAliases() {
      copyOnWrite();
      instance.clearAliases();
      return this;
    }
    /**
     * <pre>
     * DEPRECATED: This field is no longer supported. Instead of using aliases,
     * please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intended
     * aliases.
     * Additional names that this endpoint will be hosted on.
     * </pre>
     *
     * <code>repeated string aliases = 2;</code>
     */
    public Builder addAliasesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addAliasesBytes(value);
      return this;
    }

    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public java.util.List<String>
        getFeaturesList() {
      return java.util.Collections.unmodifiableList(
          instance.getFeaturesList());
    }
    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public int getFeaturesCount() {
      return instance.getFeaturesCount();
    }
    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public java.lang.String getFeatures(int index) {
      return instance.getFeatures(index);
    }
    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFeaturesBytes(int index) {
      return instance.getFeaturesBytes(index);
    }
    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public Builder setFeatures(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setFeatures(index, value);
      return this;
    }
    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public Builder addFeatures(
        java.lang.String value) {
      copyOnWrite();
      instance.addFeatures(value);
      return this;
    }
    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public Builder addAllFeatures(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllFeatures(values);
      return this;
    }
    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public Builder clearFeatures() {
      copyOnWrite();
      instance.clearFeatures();
      return this;
    }
    /**
     * <pre>
     * The list of features enabled on this endpoint.
     * </pre>
     *
     * <code>repeated string features = 4;</code>
     */
    public Builder addFeaturesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addFeaturesBytes(value);
      return this;
    }

    /**
     * <pre>
     * The specification of an Internet routable address of API frontend that will
     * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
     * It should be either a valid IPv4 address or a fully-qualified domain name.
     * For example, "8.8.8.8" or "myservice.appspot.com".
     * </pre>
     *
     * <code>optional string target = 101;</code>
     */
    public java.lang.String getTarget() {
      return instance.getTarget();
    }
    /**
     * <pre>
     * The specification of an Internet routable address of API frontend that will
     * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
     * It should be either a valid IPv4 address or a fully-qualified domain name.
     * For example, "8.8.8.8" or "myservice.appspot.com".
     * </pre>
     *
     * <code>optional string target = 101;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      return instance.getTargetBytes();
    }
    /**
     * <pre>
     * The specification of an Internet routable address of API frontend that will
     * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
     * It should be either a valid IPv4 address or a fully-qualified domain name.
     * For example, "8.8.8.8" or "myservice.appspot.com".
     * </pre>
     *
     * <code>optional string target = 101;</code>
     */
    public Builder setTarget(
        java.lang.String value) {
      copyOnWrite();
      instance.setTarget(value);
      return this;
    }
    /**
     * <pre>
     * The specification of an Internet routable address of API frontend that will
     * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
     * It should be either a valid IPv4 address or a fully-qualified domain name.
     * For example, "8.8.8.8" or "myservice.appspot.com".
     * </pre>
     *
     * <code>optional string target = 101;</code>
     */
    public Builder clearTarget() {
      copyOnWrite();
      instance.clearTarget();
      return this;
    }
    /**
     * <pre>
     * The specification of an Internet routable address of API frontend that will
     * handle requests to this [API Endpoint](https://cloud.google.com/apis/design/glossary).
     * It should be either a valid IPv4 address or a fully-qualified domain name.
     * For example, "8.8.8.8" or "myservice.appspot.com".
     * </pre>
     *
     * <code>optional string target = 101;</code>
     */
    public Builder setTargetBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTargetBytes(value);
      return this;
    }

    /**
     * <pre>
     * Allowing
     * [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), aka
     * cross-domain traffic, would allow the backends served from this endpoint to
     * receive and respond to HTTP OPTIONS requests. The response will be used by
     * the browser to determine whether the subsequent cross-origin request is
     * allowed to proceed.
     * </pre>
     *
     * <code>optional bool allow_cors = 5;</code>
     */
    public boolean getAllowCors() {
      return instance.getAllowCors();
    }
    /**
     * <pre>
     * Allowing
     * [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), aka
     * cross-domain traffic, would allow the backends served from this endpoint to
     * receive and respond to HTTP OPTIONS requests. The response will be used by
     * the browser to determine whether the subsequent cross-origin request is
     * allowed to proceed.
     * </pre>
     *
     * <code>optional bool allow_cors = 5;</code>
     */
    public Builder setAllowCors(boolean value) {
      copyOnWrite();
      instance.setAllowCors(value);
      return this;
    }
    /**
     * <pre>
     * Allowing
     * [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), aka
     * cross-domain traffic, would allow the backends served from this endpoint to
     * receive and respond to HTTP OPTIONS requests. The response will be used by
     * the browser to determine whether the subsequent cross-origin request is
     * allowed to proceed.
     * </pre>
     *
     * <code>optional bool allow_cors = 5;</code>
     */
    public Builder clearAllowCors() {
      copyOnWrite();
      instance.clearAllowCors();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.api.Endpoint)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.api.Endpoint();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        aliases_.makeImmutable();
        features_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.api.Endpoint other = (com.google.api.Endpoint) arg1;
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        aliases_= visitor.visitList(aliases_, other.aliases_);
        features_= visitor.visitList(features_, other.features_);
        target_ = visitor.visitString(!target_.isEmpty(), target_,
            !other.target_.isEmpty(), other.target_);
        allowCors_ = visitor.visitBoolean(allowCors_ != false, allowCors_,
            other.allowCors_ != false, other.allowCors_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();
                if (!aliases_.isModifiable()) {
                  aliases_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(aliases_);
                }
                aliases_.add(s);
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();
                if (!features_.isModifiable()) {
                  features_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(features_);
                }
                features_.add(s);
                break;
              }
              case 40: {

                allowCors_ = input.readBool();
                break;
              }
              case 810: {
                String s = input.readStringRequireUtf8();

                target_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.api.Endpoint.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.api.Endpoint)
  private static final com.google.api.Endpoint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Endpoint();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.api.Endpoint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Endpoint> PARSER;

  public static com.google.protobuf.Parser<Endpoint> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

