// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/experimental/experimental.proto

package com.google.api;

/**
 * <pre>
 * Experimental service configuration. These configuration options can
 * only be used by whitelisted users.
 * </pre>
 *
 * Protobuf type {@code google.api.Experimental}
 */
public  final class Experimental extends
    com.google.protobuf.GeneratedMessageLite<
        Experimental, Experimental.Builder> implements
    // @@protoc_insertion_point(message_implements:google.api.Experimental)
    ExperimentalOrBuilder {
  private Experimental() {
  }
  public static final int AUTHORIZATION_FIELD_NUMBER = 8;
  private com.google.api.AuthorizationConfig authorization_;
  /**
   * <pre>
   * Authorization configuration.
   * </pre>
   *
   * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
   */
  public boolean hasAuthorization() {
    return authorization_ != null;
  }
  /**
   * <pre>
   * Authorization configuration.
   * </pre>
   *
   * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
   */
  public com.google.api.AuthorizationConfig getAuthorization() {
    return authorization_ == null ? com.google.api.AuthorizationConfig.getDefaultInstance() : authorization_;
  }
  /**
   * <pre>
   * Authorization configuration.
   * </pre>
   *
   * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
   */
  private void setAuthorization(com.google.api.AuthorizationConfig value) {
    if (value == null) {
      throw new NullPointerException();
    }
    authorization_ = value;
    
    }
  /**
   * <pre>
   * Authorization configuration.
   * </pre>
   *
   * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
   */
  private void setAuthorization(
      com.google.api.AuthorizationConfig.Builder builderForValue) {
    authorization_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * Authorization configuration.
   * </pre>
   *
   * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
   */
  private void mergeAuthorization(com.google.api.AuthorizationConfig value) {
    if (authorization_ != null &&
        authorization_ != com.google.api.AuthorizationConfig.getDefaultInstance()) {
      authorization_ =
        com.google.api.AuthorizationConfig.newBuilder(authorization_).mergeFrom(value).buildPartial();
    } else {
      authorization_ = value;
    }
    
  }
  /**
   * <pre>
   * Authorization configuration.
   * </pre>
   *
   * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
   */
  private void clearAuthorization() {  authorization_ = null;
    
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (authorization_ != null) {
      output.writeMessage(8, getAuthorization());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (authorization_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getAuthorization());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.api.Experimental parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.Experimental parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.Experimental parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.Experimental parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.Experimental parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Experimental parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.Experimental parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Experimental parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.Experimental parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.Experimental parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.Experimental prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Experimental service configuration. These configuration options can
   * only be used by whitelisted users.
   * </pre>
   *
   * Protobuf type {@code google.api.Experimental}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.api.Experimental, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.Experimental)
      com.google.api.ExperimentalOrBuilder {
    // Construct using com.google.api.Experimental.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Authorization configuration.
     * </pre>
     *
     * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
     */
    public boolean hasAuthorization() {
      return instance.hasAuthorization();
    }
    /**
     * <pre>
     * Authorization configuration.
     * </pre>
     *
     * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
     */
    public com.google.api.AuthorizationConfig getAuthorization() {
      return instance.getAuthorization();
    }
    /**
     * <pre>
     * Authorization configuration.
     * </pre>
     *
     * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
     */
    public Builder setAuthorization(com.google.api.AuthorizationConfig value) {
      copyOnWrite();
      instance.setAuthorization(value);
      return this;
      }
    /**
     * <pre>
     * Authorization configuration.
     * </pre>
     *
     * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
     */
    public Builder setAuthorization(
        com.google.api.AuthorizationConfig.Builder builderForValue) {
      copyOnWrite();
      instance.setAuthorization(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Authorization configuration.
     * </pre>
     *
     * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
     */
    public Builder mergeAuthorization(com.google.api.AuthorizationConfig value) {
      copyOnWrite();
      instance.mergeAuthorization(value);
      return this;
    }
    /**
     * <pre>
     * Authorization configuration.
     * </pre>
     *
     * <code>optional .google.api.AuthorizationConfig authorization = 8;</code>
     */
    public Builder clearAuthorization() {  copyOnWrite();
      instance.clearAuthorization();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.api.Experimental)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.api.Experimental();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.api.Experimental other = (com.google.api.Experimental) arg1;
        authorization_ = visitor.visitMessage(authorization_, other.authorization_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 66: {
                com.google.api.AuthorizationConfig.Builder subBuilder = null;
                if (authorization_ != null) {
                  subBuilder = authorization_.toBuilder();
                }
                authorization_ = input.readMessage(com.google.api.AuthorizationConfig.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(authorization_);
                  authorization_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.api.Experimental.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.api.Experimental)
  private static final com.google.api.Experimental DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Experimental();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.api.Experimental getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Experimental> PARSER;

  public static com.google.protobuf.Parser<Experimental> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

