// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/httpbody.proto

package com.google.api;

/**
 * <pre>
 * Message that represents an arbitrary HTTP body. It should only be used for
 * payload formats that can't be represented as JSON, such as raw binary or
 * an HTML page.
 * This message can be used both in streaming and non-streaming API methods in
 * the request as well as the response.
 * It can be used as a top-level request field, which is convenient if one
 * wants to extract parameters from either the URL or HTTP template into the
 * request fields and also want access to the raw HTTP body.
 * Example:
 *     message GetResourceRequest {
 *       // A unique request id.
 *       string request_id = 1;
 *       // The raw HTTP body is bound to this field.
 *       google.api.HttpBody http_body = 2;
 *     }
 *     service ResourceService {
 *       rpc GetResource(GetResourceRequest) returns (google.api.HttpBody);
 *       rpc UpdateResource(google.api.HttpBody) returns (google.protobuf.Empty);
 *     }
 * Example with streaming methods:
 *     service CaldavService {
 *       rpc GetCalendar(stream google.api.HttpBody)
 *         returns (stream google.api.HttpBody);
 *       rpc UpdateCalendar(stream google.api.HttpBody)
 *         returns (stream google.api.HttpBody);
 *     }
 * Use of this type only changes how the request and response bodies are
 * handled, all other features will continue to work unchanged.
 * </pre>
 *
 * Protobuf type {@code google.api.HttpBody}
 */
public  final class HttpBody extends
    com.google.protobuf.GeneratedMessageLite<
        HttpBody, HttpBody.Builder> implements
    // @@protoc_insertion_point(message_implements:google.api.HttpBody)
    HttpBodyOrBuilder {
  private HttpBody() {
    contentType_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
    extensions_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int CONTENT_TYPE_FIELD_NUMBER = 1;
  private java.lang.String contentType_;
  /**
   * <pre>
   * The HTTP Content-Type string representing the content type of the body.
   * </pre>
   *
   * <code>optional string content_type = 1;</code>
   */
  public java.lang.String getContentType() {
    return contentType_;
  }
  /**
   * <pre>
   * The HTTP Content-Type string representing the content type of the body.
   * </pre>
   *
   * <code>optional string content_type = 1;</code>
   */
  public com.google.protobuf.ByteString
      getContentTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(contentType_);
  }
  /**
   * <pre>
   * The HTTP Content-Type string representing the content type of the body.
   * </pre>
   *
   * <code>optional string content_type = 1;</code>
   */
  private void setContentType(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    contentType_ = value;
  }
  /**
   * <pre>
   * The HTTP Content-Type string representing the content type of the body.
   * </pre>
   *
   * <code>optional string content_type = 1;</code>
   */
  private void clearContentType() {
    
    contentType_ = getDefaultInstance().getContentType();
  }
  /**
   * <pre>
   * The HTTP Content-Type string representing the content type of the body.
   * </pre>
   *
   * <code>optional string content_type = 1;</code>
   */
  private void setContentTypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    contentType_ = value.toStringUtf8();
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString data_;
  /**
   * <pre>
   * HTTP body binary data.
   * </pre>
   *
   * <code>optional bytes data = 2;</code>
   */
  public com.google.protobuf.ByteString getData() {
    return data_;
  }
  /**
   * <pre>
   * HTTP body binary data.
   * </pre>
   *
   * <code>optional bytes data = 2;</code>
   */
  private void setData(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    data_ = value;
  }
  /**
   * <pre>
   * HTTP body binary data.
   * </pre>
   *
   * <code>optional bytes data = 2;</code>
   */
  private void clearData() {
    
    data_ = getDefaultInstance().getData();
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Any> extensions_;
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  public java.util.List<com.google.protobuf.Any> getExtensionsList() {
    return extensions_;
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getExtensionsOrBuilderList() {
    return extensions_;
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  public int getExtensionsCount() {
    return extensions_.size();
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  public com.google.protobuf.Any getExtensions(int index) {
    return extensions_.get(index);
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  public com.google.protobuf.AnyOrBuilder getExtensionsOrBuilder(
      int index) {
    return extensions_.get(index);
  }
  private void ensureExtensionsIsMutable() {
    if (!extensions_.isModifiable()) {
      extensions_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(extensions_);
     }
  }

  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void setExtensions(
      int index, com.google.protobuf.Any value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureExtensionsIsMutable();
    extensions_.set(index, value);
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void setExtensions(
      int index, com.google.protobuf.Any.Builder builderForValue) {
    ensureExtensionsIsMutable();
    extensions_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void addExtensions(com.google.protobuf.Any value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureExtensionsIsMutable();
    extensions_.add(value);
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void addExtensions(
      int index, com.google.protobuf.Any value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureExtensionsIsMutable();
    extensions_.add(index, value);
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void addExtensions(
      com.google.protobuf.Any.Builder builderForValue) {
    ensureExtensionsIsMutable();
    extensions_.add(builderForValue.build());
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void addExtensions(
      int index, com.google.protobuf.Any.Builder builderForValue) {
    ensureExtensionsIsMutable();
    extensions_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void addAllExtensions(
      java.lang.Iterable<? extends com.google.protobuf.Any> values) {
    ensureExtensionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, extensions_);
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void clearExtensions() {
    extensions_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any extensions = 3;</code>
   */
  private void removeExtensions(int index) {
    ensureExtensionsIsMutable();
    extensions_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!contentType_.isEmpty()) {
      output.writeString(1, getContentType());
    }
    if (!data_.isEmpty()) {
      output.writeBytes(2, data_);
    }
    for (int i = 0; i < extensions_.size(); i++) {
      output.writeMessage(3, extensions_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!contentType_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getContentType());
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, data_);
    }
    for (int i = 0; i < extensions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, extensions_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.api.HttpBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.HttpBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.HttpBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.api.HttpBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.api.HttpBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.HttpBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.HttpBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.api.HttpBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.api.HttpBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.api.HttpBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.HttpBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Message that represents an arbitrary HTTP body. It should only be used for
   * payload formats that can't be represented as JSON, such as raw binary or
   * an HTML page.
   * This message can be used both in streaming and non-streaming API methods in
   * the request as well as the response.
   * It can be used as a top-level request field, which is convenient if one
   * wants to extract parameters from either the URL or HTTP template into the
   * request fields and also want access to the raw HTTP body.
   * Example:
   *     message GetResourceRequest {
   *       // A unique request id.
   *       string request_id = 1;
   *       // The raw HTTP body is bound to this field.
   *       google.api.HttpBody http_body = 2;
   *     }
   *     service ResourceService {
   *       rpc GetResource(GetResourceRequest) returns (google.api.HttpBody);
   *       rpc UpdateResource(google.api.HttpBody) returns (google.protobuf.Empty);
   *     }
   * Example with streaming methods:
   *     service CaldavService {
   *       rpc GetCalendar(stream google.api.HttpBody)
   *         returns (stream google.api.HttpBody);
   *       rpc UpdateCalendar(stream google.api.HttpBody)
   *         returns (stream google.api.HttpBody);
   *     }
   * Use of this type only changes how the request and response bodies are
   * handled, all other features will continue to work unchanged.
   * </pre>
   *
   * Protobuf type {@code google.api.HttpBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.api.HttpBody, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.HttpBody)
      com.google.api.HttpBodyOrBuilder {
    // Construct using com.google.api.HttpBody.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The HTTP Content-Type string representing the content type of the body.
     * </pre>
     *
     * <code>optional string content_type = 1;</code>
     */
    public java.lang.String getContentType() {
      return instance.getContentType();
    }
    /**
     * <pre>
     * The HTTP Content-Type string representing the content type of the body.
     * </pre>
     *
     * <code>optional string content_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      return instance.getContentTypeBytes();
    }
    /**
     * <pre>
     * The HTTP Content-Type string representing the content type of the body.
     * </pre>
     *
     * <code>optional string content_type = 1;</code>
     */
    public Builder setContentType(
        java.lang.String value) {
      copyOnWrite();
      instance.setContentType(value);
      return this;
    }
    /**
     * <pre>
     * The HTTP Content-Type string representing the content type of the body.
     * </pre>
     *
     * <code>optional string content_type = 1;</code>
     */
    public Builder clearContentType() {
      copyOnWrite();
      instance.clearContentType();
      return this;
    }
    /**
     * <pre>
     * The HTTP Content-Type string representing the content type of the body.
     * </pre>
     *
     * <code>optional string content_type = 1;</code>
     */
    public Builder setContentTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContentTypeBytes(value);
      return this;
    }

    /**
     * <pre>
     * HTTP body binary data.
     * </pre>
     *
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return instance.getData();
    }
    /**
     * <pre>
     * HTTP body binary data.
     * </pre>
     *
     * <code>optional bytes data = 2;</code>
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setData(value);
      return this;
    }
    /**
     * <pre>
     * HTTP body binary data.
     * </pre>
     *
     * <code>optional bytes data = 2;</code>
     */
    public Builder clearData() {
      copyOnWrite();
      instance.clearData();
      return this;
    }

    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public java.util.List<com.google.protobuf.Any> getExtensionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getExtensionsList());
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public int getExtensionsCount() {
      return instance.getExtensionsCount();
    }/**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public com.google.protobuf.Any getExtensions(int index) {
      return instance.getExtensions(index);
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder setExtensions(
        int index, com.google.protobuf.Any value) {
      copyOnWrite();
      instance.setExtensions(index, value);
      return this;
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder setExtensions(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      copyOnWrite();
      instance.setExtensions(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder addExtensions(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.addExtensions(value);
      return this;
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder addExtensions(
        int index, com.google.protobuf.Any value) {
      copyOnWrite();
      instance.addExtensions(index, value);
      return this;
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder addExtensions(
        com.google.protobuf.Any.Builder builderForValue) {
      copyOnWrite();
      instance.addExtensions(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder addExtensions(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      copyOnWrite();
      instance.addExtensions(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder addAllExtensions(
        java.lang.Iterable<? extends com.google.protobuf.Any> values) {
      copyOnWrite();
      instance.addAllExtensions(values);
      return this;
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder clearExtensions() {
      copyOnWrite();
      instance.clearExtensions();
      return this;
    }
    /**
     * <pre>
     * Application specific response metadata. Must be set in the first response
     * for streaming APIs.
     * </pre>
     *
     * <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    public Builder removeExtensions(int index) {
      copyOnWrite();
      instance.removeExtensions(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.api.HttpBody)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.api.HttpBody();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        extensions_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.api.HttpBody other = (com.google.api.HttpBody) arg1;
        contentType_ = visitor.visitString(!contentType_.isEmpty(), contentType_,
            !other.contentType_.isEmpty(), other.contentType_);
        data_ = visitor.visitByteString(data_ != com.google.protobuf.ByteString.EMPTY, data_,
            other.data_ != com.google.protobuf.ByteString.EMPTY, other.data_);
        extensions_= visitor.visitList(extensions_, other.extensions_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                contentType_ = s;
                break;
              }
              case 18: {

                data_ = input.readBytes();
                break;
              }
              case 26: {
                if (!extensions_.isModifiable()) {
                  extensions_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(extensions_);
                }
                extensions_.add(
                    input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.api.HttpBody.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.api.HttpBody)
  private static final com.google.api.HttpBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new HttpBody();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.api.HttpBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HttpBody> PARSER;

  public static com.google.protobuf.Parser<HttpBody> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

